### ISSUE TITLE
Revapi violation that we don't understand

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#106]
Hi (Lukas),

On the XWiki project we've had some surprise this morning :) 

```
[INFO] --- revapi-maven-plugin:0.9.5:check (revapi-check) @ xwiki-commons-repository-model ---
[INFO] Comparing [org.xwiki.commons:xwiki-commons-repository-model:jar:9.10-rc-1] against [org.xwiki.commons:xwiki-commons-repository-model:jar:9.11-SNAPSHOT] (including their transitive dependencies).
```

Lead to:

```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.9.5:check (revapi-check) on project xwiki-commons-repository-model: The following API problems caused the build to fail:
[ERROR] java.annotation.attributeValueChanged: class org.xwiki.extension.repository.xwiki.model.jaxb.ExtensionDependency: Attribute 'javax.xml.bind.annotation.XmlType' of annotation '{"id", "constraint", "repositories"}' changed value from '@javax.xml.bind.annotation.XmlType(name = "ExtensionDependency", propOrder = {"id", "constraint", "optional", "repositories"})' to 'propOrder'.
[ERROR] 
[ERROR] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:
[ERROR] {
[ERROR] "code": "java.annotation.attributeValueChanged",
[ERROR] "old": "class org.xwiki.extension.repository.xwiki.model.jaxb.ExtensionDependency",
[ERROR] "new": "class org.xwiki.extension.repository.xwiki.model.jaxb.ExtensionDependency",
[ERROR] "annotationType": "javax.xml.bind.annotation.XmlType",
[ERROR] "annotation": "@javax.xml.bind.annotation.XmlType(name = \"ExtensionDependency\", propOrder = {\"id\", \"constraint\", \"optional\", \"repositories\"})",
[ERROR] "attribute": "propOrder",
[ERROR] "oldValue": "{\"id\", \"constraint\", \"repositories\"}",
[ERROR] "newValue": "{\"id\", \"constraint\", \"optional\", \"repositories\"}",
[ERROR] "package": "org.xwiki.extension.repository.xwiki.model.jaxb",
[ERROR] "classSimpleName": "ExtensionDependency",
[ERROR] "elementKind": "class",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] }
[ERROR] -> [Help 1]
```

This concerns a class that is generated. However no changes has been brought to it.

I rebuilt tag xwiki-commons-9.10-rc-1 and then master (9.11-SNAPSHOT) and compared the generated file ExtensionDependency:

```
$ diff target/generated-sources/xjc/org/xwiki/extension/repository/xwiki/model/jaxb/ExtensionDependency.java /tmp/generated-sources/xjc/org/xwiki/extension/repository/xwiki/model/jaxb/ExtensionDependency.java 
5c5
< // Generated on: 2017.11.14 at 11:52:43 AM CET 
---
> // Generated on: 2017.11.14 at 11:42:57 AM CET 
```

Would you have any idea about what's going on?

Thanks!

**Comment by vmassol** [comment]
hmm there's something wrong... This above was coming from our CI server:
http://ci.xwiki.org/job/xwiki-commons-testrelease/749/console

However I don't reproduce locally:

```
[INFO] --- revapi-maven-plugin:0.9.5:check (revapi-check) @ xwiki-commons-repository-model ---
[INFO] Comparing [org.xwiki.commons:xwiki-commons-repository-model:jar:9.10-rc-1] against [org.xwiki.commons:xwiki-commons-repository-model:jar:9.11-SNAPSHOT] (including their transitive dependencies).
[INFO] API checks completed without failures.
```

**Comment by vmassol** [comment]
So IMO it means some ordering bug in revapi somewhere. WDYT? Is that possible?

**Comment by vmassol** [comment]
FTR I've added https://github.com/xwiki/xwiki-commons/commit/b4171cc1aea980563a88eed8044c542497560c86 till we find out what the issue is. Thanks for any help you can bring on this!

**Comment by metlos** [comment]
Hmm.. just by having a brief look at it - theoretically it could also be the jaxb version used to generate the classes. Your CI seems to be using JDK 1.8.0_121 and JAXB 2.2. What are your local versions?

**Comment by metlos** [comment]
Btw. I downloaded the jar files xwiki-commons-repository-model-9.10-rc-1.jar and xwiki-commons-repository-model-9.11-20171114.111844-8.jar from your nexus, disassembled the source and the difference is indeed there...

**Comment by vmassol** [comment]
> Btw. I downloaded the jar files xwiki-commons-repository-model-9.10-rc-1.jar and xwiki-commons-repository-model-9.11-20171114.111844-8.jar from your nexus, disassembled the ExtensionDependency class file and the difference is indeed there...

That's weird. Let me check that too (I only rebuilt from source and didn't check the JARs). Thanks

**Comment by vmassol** [comment]
@metlos Ok I've retested everything and it seems there was some big mistake during our 9.10RC1 release and some wrong jars got uploaded in our repo (while the good ones were uploaded on maven central, both with the same name). So depending on which ones you had in your local repo the build would fail on revapi or not.

Good that revapi helped us find this issue! :)

Thanks for your help again
