### ISSUE TITLE
Maven plugin doesn't run analysis if no old version is present

### ISSUE THREAD

**Issue by mkavanagh** [revapi/revapi#109]
When invoking revapi analysis for a Maven project (e.g. via `revapi:check` or `revapi:update-versions`), the analysis will be skipped if no prior versions of the artifact are available.

Generally this makes sense (because most checks relate to the difference between two versions), but it is possible to have checks that detect defects rather than differences (e.g. `java.class.nonPublicPartOfAPI`) - these will flag up later when a first version has been published, but it would be better to flag them up when they are introduced by running analysis for these checks even if no prior artifact exists.

**Comment by metlos** [comment]
Fixed in `revapi-maven-plugin-0.10.0`
