### ISSUE TITLE
Maven plugin does not compare dependencies

### ISSUE THREAD

**Issue by glianeric** [revapi/revapi#110]
Hello,

  Perhaps I am misunderstanding how revapi works; I have a particular requirement to analyze a project and its dependencies in the following manners:

1)  Project B depends on Project A.   When performing a comparison of B's jar's, I would also like to see a report of a comparison of A's jars if the two versions of B used different versions of A.

2)  Same as above, but looking to go straight down the dependency tree of a WAR.  In essence, I would like to see the impact of versions changes of the company's own dependencies on the application.

Put in plain words, I would like the option to compare things that are not part of the reactor build, more specifically, I wish to compare dependencies.   Source jars may or may not be available for the dependencies.

It seems like it is not possible to do this out-of-the-box, but just in case I'm not understanding the configuration correctly, is this possible?

If not, I would like to request this as a feature.

**Comment by metlos** [comment]
Hi,

> Project B depends on Project A. When performing a comparison of B's jar's, I would also like to see a report of a comparison of A's jars if the two versions of B used different versions of A.

Revapi distinguishes between artifacts and their dependencies. The artifacts are considered the API that is primarily checked, BUT if this API exposes in some form or fashion any classes from the dependencies then those are also considered part of the API and check also (recursively).

So, by default, Revapi won't check classes from A unless B somehow "publicizes" them in its API.

> Same as above, but looking to go straight down the dependency tree of a WAR. In essence, I would like to see the impact of versions changes of the company's own dependencies on the application.

Wars should be handled as normal jar files. As long as the dependencies are declared in the POM, Revapi should find out about them.

> Source jars may or may not be available for the dependencies.
Revapi actually doesn't require source files at all. It strictly works with the compiled classes.

> Put in plain words, I would like the option to compare things that are not part of the reactor build

Right now, you can use the `oldArtifacts` and `newArtifacts` configuration properties of the maven plugin to explicitly specify the artifacts you want to consider your primary API. Their dependencies get resolved and the process continues as explained above.

If you wanted to also consider the dependencies as part of the primary API (i.e. consider them the same as the artifacts of  the current project or the explicit `oldArtifacts` and `newArtifacts`) you would have to modify the maven plugin. The change should be fairly simple. The maven plugin resolves the artifacts of the API and the dependencies and then supplies them to the analysis to Revapi itself. All you'd need to do is that you would merge the two lists and provide everything as the "primary" API to Revapi for analysis. PR would be more than welcome 😉

**Comment by glianeric** [comment]
Hi metlos, 

  Thanks for the response!   I am not a developer but I can write code - I just don't have experience.  This sounds like an interesting opportunity.  I'll work on a PR but it is likely that I will be slow with it.

  If you don't mind a question, how does revapi determine that an API is publicized?  While there are declared interfaces and those are used by various classes, what are the rules for detecting them?

A bit of background:
I am basically dealing with a situation where a WAR packages components that are built in another process along with war-specific spring configuration for those components.  The WAR obviously declares such components as its dependencies, and those components have dependencies of their own.  Naturally I want to filter the analysis by groupId - the feature is already there which is great.

**Comment by metlos** [comment]
> Thanks for the response! I am not a developer but I can write code - I just don't have experience. This sounds like an interesting opportunity. I'll work on a PR but it is likely that I will be slow with it.

That would be awesome, thank you!

Almost all work required would I think happen around https://github.com/revapi/revapi/blob/master/revapi-maven-plugin/src/main/java/org/revapi/maven/Analyzer.java#L330. Basically you want everything that is currently passed to the `supportedBy` be merged with the main set of archives and supplied to `API.of()` instead. Note though that I would like this to be "guarded" by a configuration property of the revapi goals which you would probably add into https://github.com/revapi/revapi/blob/master/revapi-maven-plugin/src/main/java/org/revapi/maven/AbstractRevapiMojo.java and pass it down to the `Analyzer` class which does the artifact resolution and invokes the analysis.

> If you don't mind a question, how does revapi determine that an API is publicized? While there are declared interfaces and those are used by various classes, what are the rules for detecting them?

Revapi categories the uses of types. It assumes some types of uses are moving the type to the API, some don't. See https://github.com/revapi/revapi/blob/master/revapi-java-spi/src/main/java/org/revapi/java/spi/UseSite.java#L85

Whenever a type becomes part of the API, all types it or any of its fields/methods are using, become part of the API, too, recursively.

**Comment by glianeric** [comment]
Hi metlos,
  I absolutely envisioned guarding this with a switch which is 'false' by default.  :)

  Thanks for the information, it really helps!
