### ISSUE TITLE
No documentation for "ability to filter by annotation presence" feature

### ISSUE THREAD

**Issue by rmetzger** [revapi/revapi#13]
I'm currently comparing different java API compatibility checkers, and I found revapi interesting because it seems to support exclusion/inclusion for the API check based on annotations.

However, I didn't find any documentation how to use it.

**Comment by metlos** [comment]
Yes, the website and therefore docs are now more than lacking ;) I currently struggle to find time to work on revapi as much as I should.

For now, here's some info:
The filtering by annotation (i.e. ignoring elements based on presence of an annotation on them) is configured under "revapi.java.ignore.annotated" in the config json and must conform to this schema: https://github.com/revapi/revapi/blob/master/revapi-java/src/main/resources/META-INF/ignore-by-annos-schema.json

Some simple examples can be found in the testsuite: https://github.com/revapi/revapi/blob/master/revapi-java/src/test/java/org/revapi/java/IgnoreByAnnotationFilterTest.java

**Comment by rmetzger** [comment]
Thank you for the info. I'll try it out soon.

**Comment by rmetzger** [comment]
It seems to me that inclusion of checks if an annotation is present is not supported yet, right?
I'm looking for a tool which verifies that all interfaces annotated with `@PublicAPI` are checked.

**Comment by metlos** [comment]
Right, that's not yet supported, but should be doable fairly easy.

**Comment by metlos** [comment]
At last, the new site is live. Also the ignoring by annotations got some upgrades.

Check out http://revapi.org/modules/revapi-java/extensions/annotated-elem-filter.html.
