### ISSUE TITLE
Maven plugin update-version and update-release-properties wrong new version number when revapi.semver.ignore is enabled

### ISSUE THREAD

**Issue by mschmidae** [revapi/revapi#132]
The Maven plugins update-release-properties and update-versions produces wrong SemVer-Numbers, when revapi.semver.ignore is enabled.

Example:
Old Version: 1.0.1
Change: java.method.added
Change Level: NON_BREAKING_CHANGES
Expected new Version: 1.1.0

The new version number will be correct calculated, when revapi.semver.ignore is disabled.

When revapi.semver.ignore is enabled, the calculated version number will be 2.0.0 because ApiBreakageHintingReporter reports in this case Change Level = BREAKING_CHANGES.

**Comment by metlos** [comment]
Wow, this bug has been there for a looong time. Thanks for reporting it!

**Comment by metlos** [comment]
should be fixed in `revapi-maven-plugin-0.10.3`.
