### ISSUE TITLE
When using revapi.singleVersionForAllModules, a version tag is added to each child POM.

### ISSUE THREAD

**Issue by glianeric** [revapi/revapi#135]
Hi,

  As per the title:  When using revapi.singleVersionForAllModules, a version tag is added to each child POM.

  This is not desirable when using update-versions or update-release properties when the version is inherited from the parent POM.  Would it be possible to change how this works, or add an option to turn this behavior on/off?

**Comment by metlos** [comment]
I imagine it could work the same as `mvn versions:set`. Could you maybe please help me out with investigating how that behaves when:
* running from the root of the multimodule build
* running on one module of a multimodule build
* running on a module with the parent pom being completely external
* any other scenario that you want supported or find potentially unclear

Thanks!

**Comment by glianeric** [comment]
Hi metlos, thanks for the quick reponse!  You are right, it should be the same behavior as versions:set in my view :)

I will respond to the scenarios in order.  The command I run in each case:

mvn package revapi:update-versions -Drevapi.singleVersionForAllModules=true -Djavax.xml.accessExternalSchema=all

1)  The parent POM version is changed correctly, to reflect the highest level change (ie. breaking)
     The module POMs have a version tag (same version as above) inserted, but they should inherit it from the top level POM instead.
     This is the main scenario that I am concerned about.

2)  The module POM has a version tag inserted according to its own changes.  The parent POM is not affected.  I think case, no version tag should be inserted and also an error should be printed OR it should attempt running this 'from root'.

3)  Same as 2 above, but obviously in this case we are not able to run from root, so that option is taken away.  In this case it would be nice if an error was printed.

In general, I believe that if not running from root while specifying revapi.singleVersionForAllModules=true, the response should be an error advising me or the ... error of my ways :D

**Comment by metlos** [comment]
This is now fixed in `revapi-maven-plugin:0.11.5`.
