### ISSUE TITLE
Remove the "newArchive"/"oldArchive" parameters from the Maven plugin output as they are optional and cause build failures during releases

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#137]
Hi, on the xwiki project we've noticed that Revapi added recently "newArchive"/"oldArchive"... As a consequence our developers started copy pasting those into your pom.xml ignore list.

For example: 
* https://github.com/xwiki/xwiki-platform/commit/975f4d510f311891f6bf51c0afa422b367804463
* https://github.com/xwiki/xwiki-platform/commit/1f651b34f34ef16cb9fc5b4c402c6cb5c68b802d

When the release time comes this is breaking the build. I would really prefer not to have to develop some extra Maven Enforcer checks to verify that these optional parameters are not set in our poms.

Do you think it would be possible to not display them in the console output or in a way that doesn't make the developer copy paste them in the pom.xml as ignores? :)

Thanks a lot Lukas

**Comment by mflorea** [comment]
The problem seems to be that the version (e.g. 10.6-SNAPSHOT) is not updated by the release plugin and so the build fails on ``release:perform`` when building the 10.6-rc-1 version (tag) for instance.

**Comment by metlos** [comment]
Yep, that would be the case. The output is meant as "here is all I know about the difference. Pick and choose what uniquely identifies it in your case".

So usually, almost all attributes can be deleted.

Maybe I could somehow define what attributes are mandatory for different types of problems, but then it would become more involved for the users to find out what else can be used to identify changes.

While in your case, you choose to explicitly list each and every change (which is of course completely valid approach), other users tend to use the additional attributes to ignore whole swaths of different problems by using the more "generic" attributes like the "oldArchive" and "newArchive".

So I'm a bit torn on this. I agree that including all attributes on all differences is kinda redundant but removing them from the output will make the attributes much less discoverable.

**Comment by vmassol** [comment]
> So I'm a bit torn on this. I agree that including all attributes on all differences is kinda redundant but removing them from the output will make the attributes much less discoverable.

Yes, not easy choice :)

It was fine with the other parameters in the past. It's only this new one"newArchive"/"oldArchive" that causes a problem.

I don't have a perfect solution for you either ATM...

**Comment by metlos** [comment]
What do you say about output like this?

```
If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:

{
  "code": "java.class.nonPublicPartOfAPI",
  "new": "class Main.Inaccessible",
  "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
  /*
  Additionally, the following attachments can be used to further identify the difference:

  "classSimpleName": "Inaccessible",
  "newArchive": "first-version-checks:first-version-checks:jar:1.0.0",
  "exampleUseChainInNewApi": "Main.Inaccessible is returned from method Main.Inaccessible Main::failingMethod() (method Main.Inaccessible Main::failingMethod() is part of the API)",
  "package": "",
  "classQualifiedName": "Main.Inaccessible",
  "elementKind": "class",
  */
},
```

**Comment by vmassol** [comment]
I'm a bit ambivalent about this. 

Question: is the following working (i.e. without the version):

```
"newArchive": "first-version-checks:first-version-checks:jar",
```
?

(sorry I should try it but I don't have an example at hand to try it on easily and quickly)

If it works, then maybe that could be the default, since this is what is causing our problem and will cause problems to everyone else using maven to release (during release the artifact version is modified by the maven release plugin and thus revapi reports a violation)?

**Comment by vmassol** [comment]
The new maven property will be very good for us:
https://github.com/revapi/revapi/commit/50dd8725d670e3349aa71993145d67bbb46e12a6#diff-46f21e20c68274c6ac8c01470e6a41acR58

It will only output the minimal to identify the ignore, right?

If so that's perfect :)

Any idea when this could be released? We just hit the issue again during the release (and every time we loose like 4-5 hours ;)).

**Comment by metlos** [comment]
Should be implemented in maven plugn 0.10.5 by the new `outputNonIdentifyingDifferenceInfo` property.

**Comment by vmassol** [comment]
Thanks @metlos ! Will try it ASAP.

**Comment by vmassol** [comment]
It's ok now.
