### ISSUE TITLE
Surprinsing nowCheckedException

### ISSUE THREAD

**Issue by tmortagne** [revapi/revapi#141]
The following change generated a nowCheckedException: https://github.com/xwiki/xwiki-rendering/commit/6fdd3002fdcdcadeccd755ec65bdbff93f3bb9c7#diff-0ddb9da630610a0b1302d968f537d522L28

The documentation suggest that nowCheckedException is produced when a class suddenly start to extends Exception but it's almost the opposite here (it still extends Exception but indirectly).

It also produce a nonFinalClassInheritsFromNewClass but I was expecting this one (even if here it's a false positive in practice since I don't see how this could cause any issue).

**Comment by metlos** [comment]
Thanks for reporting this. The logic for detecting whether a class has become a checked exception is indeed incorrect.

I'm working on a fix.

**Comment by metlos** [comment]
Should be fixed in `revapi-java-0.18.2`.

**Comment by tmortagne** [comment]
Thanks !
