### ISSUE TITLE
There does not seems to be any tag for revapi-java 0.18.1 and 0.18.2

### ISSUE THREAD

**Issue by tmortagne** [revapi/revapi#143]
At least I can't find them on https://github.com/revapi/revapi/releases. Direct link like https://github.com/revapi/revapi/releases/tag/revapi-java-0.18.1 or https://github.com/revapi/revapi/tree/revapi-java-0.18.1 does not work either.

**Comment by metlos** [comment]
thanks, I just pushed the tags to the repo. I keep forgetting to do that...
