### ISSUE TITLE
maven-plugin not skipping sub-modules on 0.11.0

### ISSUE THREAD

**Issue by rfer** [revapi/revapi#148]
I have a scenario with Revapi configured on the root pom, but to be skipped on some sub-modules.

This allows me to compile those submodules individually without having to run the plugin.

I'm doing so by adding the following config to the sub-module's pom:
```
    <build>
        <plugins>
            <plugin>
                <groupId>org.revapi</groupId>
                <artifactId>revapi-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

However, since 0.11.0, this stopped working.

Looking at the difference in the pom between 0.10.5 and 0.11.0, I can't see anything that could have impacted this.

**Comment by metlos** [comment]
Interesting... Have you tried looking at the effective pom of the submodules?

Just run `mvn help:effective-pom` at the root and it will also print out the effective pom of all the submodules. There you should be able to see what is the config that maven uses in each module.

From a quick look at the code, I can't see what could have gone wrong either.

**Comment by rfer** [comment]
Thanks for getting back.

I'll take a look when as soon as I can.

However, it's strange that just reverting back to 0.10.5 it works as expected.

**Comment by metlos** [comment]
hmm.. that is weird... would you be able to point me to your sources, or if not possible, to some test project where the behavior would be reproducible?

**Comment by metlos** [comment]
I've added a simple integration test that illustrates how I understand your issue, but it passes correctly. Would you mind modifying it so that it matches your exact situation and fails? https://github.com/revapi/revapi/tree/master/revapi-maven-plugin/src/it/build/skip-override

**Comment by metlos** [comment]
Please re-open this issue with more details or a reproducer if it is still happening. The integration test seems to be covering this case as far as I can tell.
