### ISSUE TITLE
Standalone `revapi.bat` doesn't run `revapi`

### ISSUE THREAD

**Issue by YuriGeinishBC** [revapi/revapi#150]
The bat file is a stub. Here's an easy workaround to run `revapi`. Replace the bat contents with:

    java -cp lib/*;conf org.revapi.standalone.Main revapi.bat . %*

**Comment by metlos** [comment]
Blindly applied, thank you! :smile:

**Comment by YuriGeinishBC** [comment]
@metlos Well, in this case (didn't think you'd use it), here is the fully-functional version, identical to the bash script (except it doesn't build the `CLASSPATH` variable, because `java` can take a `dirname/*` pattern which will use every jar in the directory):

    @echo off
    
    if "%JAVA_HOME%" == "" (
        set "JAVA_EXE=java"
    ) else (
        set "JAVA_EXE=%JAVA_HOME%\bin\java.exe"
    )

    set "mydir=%~dp0"

    "%JAVA_EXE%" -cp "%mydir%\lib\*;%mydir%\conf" org.revapi.standalone.Main revapi.bat . %*

**Comment by metlos** [comment]
Thank you for the update! I have no experience with batch files nor any way of testing this (pure linux household and workplace) but it looks reasonable, so I'm just believing you it works :)
