### ISSUE TITLE
Build fails when combining semver.ignore and reclassify through pipeline configuration

### ISSUE THREAD

**Issue by Singleton06** [revapi/revapi#152]
Build Log:
https://gist.github.com/Singleton06/e60d74715040af62ff09908308585ab7

Repository showing the issue:
https://github.com/Singleton06/revapi-issue-reproduction

I've had added @metlos  as a collaborator to the project.

Specific configuration for RevAPI:
https://github.com/Singleton06/revapi-issue-reproduction/blob/master/v2/pom.xml#L27-L83

**Comment by metlos** [comment]
The fix in 2664b48 should get rid of the repetitions of the differences.

Your project will still fail though but this time in an expected manner :) You're reclassifying your findings as `NON_BREAKING` yet you are only allowing `EQUIVALENT` changes in patch version increase. Once you amend that, the project will build correctly (when using revapi built from the current master (at least https://github.com/revapi/revapi/commit/adb5ef7f819aec7611e66aa00b73239623ee14c0)).

**Comment by Singleton06** [comment]
True.  I had tried minor version bumps as well without much luck either, I just had the wrong value in the sample.

Thank you for looking into this so quickly.  Just curious, what would the turn-around be for a release?  We're looking to hook this up to 100+ projects, but this is something that we'd need to have fixed before we're willing to do that.

**Comment by metlos** [comment]
I've released new versions that should work for you. In particular, make sure to use the new `revapi-maven-plugin:0.11.1`.

**Comment by Singleton06** [comment]
Just to circle back on this, this appears to be working.  Thank you!
