### ISSUE TITLE
Windows Users Can't Clone Repo

### ISSUE THREAD

**Issue by Singleton06** [revapi/revapi#156]
When I go to clone the project on a windows machine it fails:
https://gist.github.com/Singleton06/3f76c3d1a40e54820f12bef438997d6a

This SO post seems to fit what the issue might be here since the file contains a *:
https://stackoverflow.com/questions/26097568/git-pull-error-unable-to-create-file-invalid-argument

**Comment by metlos** [comment]
Should be fixed now on master

**Comment by Singleton06** [comment]
Worked!
![image](https://user-images.githubusercontent.com/2235110/57664801-29ae4180-75bf-11e9-8f1c-e9cd01d3e786.png)
