### ISSUE TITLE
Some Checks Are Not Detected On Windows

### ISSUE THREAD

**Issue by Singleton06** [revapi/revapi#157]
I have noticed that certain issues are detected in Linux causing the build to fail but seem to pass without an issue on Windows.  One example that I have noticed of this is the "java.class.externalClassExposedInAPI" code.  

Here is an example project:
https://github.com/Singleton06/revapi-issue-reproduction/tree/os-build-diff

I then built this on linux (which had a failure) and then built it on Windows (which passes).

Linux Build:
![image](https://user-images.githubusercontent.com/2235110/57657336-ada50100-75a0-11e9-94b8-632b7a6bd9cc.png)

Windows Build:
![image](https://user-images.githubusercontent.com/2235110/57657374-cd3c2980-75a0-11e9-8e73-79baae01b382.png)

The other failures I have noticed seem to occur during dependency checks.  I'll keep my eye out for any additional ones that I notice.

**Comment by Singleton06** [comment]
I was curious so I attempted to run mvn clean install on the revapi project from my windows machine:
![image](https://user-images.githubusercontent.com/2235110/57717728-789cbb00-7641-11e9-92be-f3790d06af68.png)

It looks like this might also point to the same issue as well

**Comment by metlos** [comment]
Perfect! Now all I need is a Windows VM...

**Comment by metlos** [comment]
Just informing that I finally was able to get myself a Windows VM (how cool is it of MS to provide them for dev for free?) and reproduce the issue. I have no idea why the test failures happen though. If you were able to gain any insight, I'd love to hear about it.

**Comment by metlos** [comment]
Would you please try if this is still reproducible with the just released `revapi-java:0.20.1`?

**Comment by metlos** [comment]
I am going to assume this is fixed with `revapi-java:0.20.1`. If the problem persists, please reopen the issue.
