### ISSUE TITLE
Removing 'default' modifier and adding checked exception Not Matching

### ISSUE THREAD

**Issue by whatisnormal** [revapi/revapi#158]
Hello,
I have an interface method which I removed the "default" modifier and added a "throws Exception" statement, and I want to ignore this statement as a breaking change.

`
method void com.company.component.Service::onDestroy()

method void com.company.component.Service::onDestroy() throws java.lang.Exception
`

It outputs the following

`
Reason: java.method.exception.checkedAdded: Method newly throws checked exceptions: java.lang.Exception.
NON_BREAKING BINARY
BREAKING SOURCE

Reason: java.method.noLongerDefault: The interface no longer has the default implementation of the method.
BREAKING BINARY
BREAKING SOURCE

Reason: java.method.nowAbstract: Method now abstract
BREAKING BINARY
BREAKING SOURCE
`

I already tried to match multiple ways but it never matches...

1)

`
   {
        "code" : "java.method.exception.checkedAdded",
        "old" : "method void com.company.component.Service::onDestroy()",
        "new" : "com.company.component.Service::onDestroy() throws java.lang.Exception",
        "justification": "ABC"
      },
      {
        
        "code"           :  "java.method.nowAbstract",
        "old"            :  "method void com.company.component.Service::onDestroy()",
        "new"            :  "method void com.company.component.Service::onDestroy() throws java.lang.Exception",
        "justification"  :  "DEF"
      },
      {
        "code"           :  "java.method.noLongerDefault",
        "old"            :  "method void com.company.component.Service::onDestroy()",
        "new"            :  "method void com.company.component.Service::onDestroy() throws java.lang.Exception",
        "justification"  :  "XYZ"
      }

`

2)

`
 {
        "regex"          : true,
        "code"           :  "java\.method\..*",
        "old"            :  "[^ ]* com\.company\.component\.Service.*",
        "justification"  :  "XYZ"
      }
`

Help here is appreciated, pleaaasee

**Comment by metlos** [comment]
I would appreciate if you could provide a simple github project where I could reproduce your issue like in #157. This really helps me to get to the bottom of the issue quickly without spending the little free time I have for revapi second-guessing.

**Comment by whatisnormal** [comment]
Thanks for your reply Lukas. I will create a simple github project and try
to reproduce, apart that the conditions are not exactly the same and is
hard to mimic.

Meanwhile, if you were to wild guess, what would be your pointers?

Lukas Krejci <notifications@github.com> escreveu no dia segunda, 20/05/2019
à(s) 18:59:

**Comment by whatisnormal** [comment]
Found the problem. It was related with -Drevapi.ignore={file.path} maven property where I was pointing to the relative path and not the absolute path. With the last, it works 🤷‍♂
