### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [revapi/revapi#160]
Hi
The following lines have cryptographic API misuses. <br> File name => revapi-java/src/main/java/org/revapi/java/checks/common/SerializationChecker.java: Line number => 562: API name => MessageDigest:<BR> File name => revapi-java/src/main/java/org/revapi/java/checks/common/SerializationChecker.java: Line number => 313: API name => MessageDigest:First parameter (with value "SHA") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => revapi-java/src/main/java/org/revapi/java/checks/common/SerializationChecker.java: Line number => 562: API name => MessageDigest:<BR> File name => revapi-java/src/main/java/org/revapi/java/checks/common/SerializationChecker.java: Line number => 561: API name => MessageDigest:First parameter (with value "SHA") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => revapi-java/src/main/java/org/revapi/java/checks/common/SerializationChecker.java: Line number => 314: API name => MessageDigest:<BR> File name => revapi-java/src/main/java/org/revapi/java/checks/common/SerializationChecker.java: Line number => 314: API name => MessageDigest:<BR>

**Comment by metlos** [comment]
Spam, closing. https://github.com/mob41/broadlink-java-api/issues/22
