### ISSUE TITLE
latest version set?

### ISSUE THREAD

**Issue by monperrus** [revapi/revapi#163]
Hi, I'm currently using the versions `revapi-maven-plugin=0.9.5 org.revapi=0.14.4 revapi-reporter-text=0.8.1`.

What's the most recent version combination of `revapi-maven-plugin+revapi-java+revapi-reporter-text`? Thanks!

**Comment by metlos** [comment]
The latest versions should be compatible.. http://revapi.org/downloads.html

**Comment by monperrus** [comment]
Thanks, I looked for this page. Now tyring with `revapi-maven-plugin=0.11.1 org.revapi=0.19.1 revapi-reporter-text=0.10.1`.
