### ISSUE TITLE
Arguments to package private interface seen as part of the public api

### ISSUE THREAD

**Issue by mpkorstanje** [revapi/revapi#164]
Given a package private interface `StepDefinitionMatch` referencing a `TestCaseState` class:

```java
interface StepDefinitionMatch {
    void runStep(TestCaseState state) throws Throwable;

    void dryRunStep(TestCaseState state) throws Throwable;

    String getCodeLocation();

}
```

I get the following violation on a package private implementation of `StepDefinitionMatch`:

```
[ERROR] java.class.nonPublicPartOfAPI: class io.cucumber.core.runner.TestCaseState: Class 'io.cucumber.core.runner.TestCaseState' is indirectly included in the API (by the means of method return type for example) but the class is not accessible (neither public nor protected). (breaks semantic versioning)
```
I think rev api only looks at the at the method modifier (public because implementation of an interface) rather then at the class + method modifier.

**Comment by metlos** [comment]
Further up the maven output Revapi should have mentioned why it considers this an error - it should output the use-chain leading from the package-private class up to some public API member. Could you share that as well?

**Comment by mpkorstanje** [comment]
Aah. I totally overlooked that. I thought it was part of the information needed to add an exclusion and not material to analyzing the problem.
