### ISSUE TITLE
RevAPI succeeds randomly, although there appears to be an API break

### ISSUE THREAD

**Issue by cdir** [revapi/revapi#169]
Although it seems like I have an API problem in my library, revapi maven plugin sometimes succeeds and sometimes fails. If I am running `mvn clean install` in succession it succeeds about half the time but not alternately.

The API problem is the following.

```
The following API problems caused the build to fail:
[ERROR] java.class.nonPublicPartOfAPI: class org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: Class 'org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer' is indirectly included in the API (by the means of method return type for example) but the class is not accessible (neither public nor protected). [org.springframework.security:spring-security-config:jar:5.1.6.RELEASE
```
I have spring security as references library but I think it is not realy related to spring security. But looking at the referenced class it seems like spring is not clear in API indeed.

In the attached ZIP is a minimal project setup with my revapi config where I can reproduce the problem. There is also a json file that already excludes some other breaking changes.

[revapi-random-test.zip](https://github.com/revapi/revapi/files/3805987/revapi-random-test.zip)

**Comment by metlos** [comment]
I've released `revapi-java:0.20.1` which should have this fix. Thanks for reporting and for the reproducer!
