### ISSUE TITLE
Surprising java.generics.formalTypeParameterRemoved for T to java.lang.Object

### ISSUE THREAD

**Issue by tmortagne** [revapi/revapi#170]
Revapi is complaining about the following change: 
The exact change that leaded to this error is https://github.com/xwiki/xwiki-platform/commit/e2805f9b48a2a81ee20e8ffa2bbaea63cc49f03f#diff-4548573dff4504f640cf1206da580737R113 with

```
[INFO] The following API problems caused the build to fail:
[INFO] java.method.parameterTypeParameterChanged: parameter <S> S org.xwiki.extension.script.AbstractExtensionScriptService::safe(===java.lang.Object===): The type parameter of method parameter changed. The original type was 'T extends java.lang.Object'while the new type is 'java.lang.Object'.
[INFO] java.generics.formalTypeParameterRemoved: method <S> S org.xwiki.extension.script.AbstractExtensionScriptService::safe(java.lang.Object): The formal type parameter 'T' was removed from the element.
[INFO] 
[INFO] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:

{
  "code": "java.method.parameterTypeParameterChanged",
  "old": "parameter <S, T> S org.xwiki.extension.script.AbstractExtensionScriptService::safe(===T===)",
  "new": "parameter <S> S org.xwiki.extension.script.AbstractExtensionScriptService::safe(===java.lang.Object===)",
  "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
},
{
  "code": "java.generics.formalTypeParameterRemoved",
  "old": "method <S, T> S org.xwiki.extension.script.AbstractExtensionScriptService::safe(T)",
  "new": "method <S> S org.xwiki.extension.script.AbstractExtensionScriptService::safe(java.lang.Object)",
  "typeParameter": "T",
  "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
},
```

I have a hard time understanding how changing a parameter type from a generic `T` to Object would be "a source incompatible change" (according to https://revapi.org/modules/revapi-java/differences.html#a_formal_type_parameter_removed). Revapi should probably check if the new type is different from the type that used to be extended by the generic.

**Comment by metlos** [comment]
While you are right this is OK in most circumstances if the new type corresponds to the original bound of the type parameter.

But you can call the methods with explicitly defined bounds (this is less required in java 8+ but still a valid and sometimes required syntax):

```java
String parameter = ...;
AbstractExtensionService service = ...;
String result = service.<String, String>safe(parameter);
```

I believe this will fail to compile with the new version of the library (even though I haven't actually checked).

**Comment by tmortagne** [comment]
```String result = service.<String, String>safe(parameter);```

Indeed you are right. This won't compile and I should have though about it...
