### ISSUE TITLE
is fixing "Non-Public Part of API" a really an API break ?

### ISSUE THREAD

**Issue by sbernard31** [revapi/revapi#172]
Hi,
  We begin to use **revapi**. It sounds a real great tool. :heart_eyes: 
  Without surprise our API is a bit inconsistent and our code contains some Non-Public Part of API, mainly `public` attributes typed with a `private` class.

  We also activate semantic versioning, and begin to fix this Non-Public Part of API by making the attribute `private` but this will break the API, as a public attribute is now private.
  But in practice this attribute was pretty much impossible to use as this is not possible to declare a variable of its type. So should revapi should raise this kind of API break ?

  (I know a "non breaking" way could be to just set the class as public, but this could not  be the "real" fix)

**Comment by metlos** [comment]
Well, you're of course right that this "condition" breaks neither binary nor source compatibility and as such it is not an API breakage per se.

But it is my personal opinion that it is a "smell" in the API and should at least be marked as such. You can set up Revapi to ignore the concrete changes you "inherit" from the past. I believe it is still useful to break the build on any new occurrence of this type of semantic API problem.

See https://revapi.org/modules/revapi-basic-features/extensions/ignore.html to see how to ignore concrete differences.

**Comment by sbernard31** [comment]
I think there is a misunderstanding.

I agree that "Non-Public Part of API" means that the API is inconsistent. and I agree that this is a nice feature to report this.

But this is not really my point. Let's try to explain, imagine I release a version 1.0.0 with a public class "A" with a public  attribute "a" typed with a private class B.

Now I begin a 1.1 version.
I add revapi to check that I didn't break any API.
And it detect that "a" is typed with the private class "B".
So I want to fix it by making "a" as private, but this will create a "real" API breakage as a public attribute is now private.

My guess is this is not a real API break and maybe revapi should not raise it ?
Why because in real world the usage of this field was impossible as its type was private and so nobody can use it. Am I right or did I missed something ? (or maybe it's just to hard  to code?)

**Comment by metlos** [comment]
Huh, I completely forgot about the fact that this is actually configurable :)

https://revapi.org/modules/revapi-java/index.html#class_is_non_public_part_of_api

The default is to always report these kinds of problems, even if they existed in the old version. But Revapi can be configured to ignore these errors if they already existed in the previous version.

The default is set up this way to warn even the new users such as yourself about these issues.

So, you have a couple of choices here:
* configure Revapi to ignore existing non-public API problems as mentioned above
* ignore just the specific problems
* fix your API

**Comment by sbernard31** [comment]
Last try :grin:, because I still feel that you don't really get my question.

I ask myself if in this [particular case](https://github.com/revapi/revapi/issues/172#issuecomment-566171754) this makes sense that revapi raises the "public to private"  break (not the Non-Public Part of API)  as this is pragmatically impossible that someone was using this public field, and so in practice, it seems to me there is no break.

thx for your time :pray:

**Comment by metlos** [comment]
Ok, you finally got me to really read your question, sorry :)

> "A" with a public attribute "a" typed with a private class B.
> 
> Now I begin a 1.1 version.
> I add revapi to check that I didn't break any API.
> And it detect that "a" is typed with the private class "B".
> So I want to fix it by making "a" as private, but this will create a "real" API breakage as a public attribute is now private.
>
> My guess is this is not a real API break and maybe revapi should not raise it ?

It is a real API breakage IMHO, because with 1.0.0 you could do `Object val = new A().a;` and for example log it somewhere or god forbid synchronize on it using methods available on the Object class (or any more concrete super class that is visible to the calling code). In your 1.1.0 it is not possible any more because you made `A.a` a private field.

**Comment by sbernard31** [comment]
Ok I get it  and I think you're right ! Thx again for your time ! :pray:
