### ISSUE TITLE
API checks yield errors on Windows, work fine on OSX

### ISSUE THREAD

**Issue by aldaris** [revapi/revapi#173]
I've been trying to investigate an odd issue that I can only see on Windows. The Java API changes look something like this:

```
public interface Context {
}
public interface MessageContext extends Context, MessageInfoContext {
}
public interface MessageInfoContext extends Context {
}
```
A new getRootId() method was added to the Context interface.
The corresponding change ignore entry is this:
```
{
          "code": "java.method.addedToInterface",
          "new": "method java.lang.String com.mycompany.Context::getRootId()",
          "justification": "Foo"
}
```

This all works fine on OSX, and I get a successful build, but on Windows I'm getting errors about the same method just with an extra "@ + classname" suffix for the MessageInfoContext and MessageContext classes.

I've been trying to debug this for a while, and I haven't really got too far with this. What I can see is that on Windows all the libraries are coming from system classpath for whatever reason, and the API tree is built up containing just the files from the current Maven module. On OSX on the other hand the API tree contains transitive dependencies, and the components are no longer coming from system classpath, but everything is coming as a Maven archive instead.

I would think if anything, this should have resulted in more failures, but for whatever reason it looks like that the API tree on OSX is missing classes that the Windows tree has... 
(I've also seen that the ClasspathScanner#determineApiStatus method had different outcomes on a per iteration basis.)
I'm not really sure what's going on.

**Comment by metlos** [comment]
Thanks for investigation. This indeed looks quite strange. All of the things you mention are concerning me as well..

**Comment by aldaris** [comment]
I think the determineApiStatus note could be a red herring, I *think* the HashSet/Map ordering is different on the two platforms, which may explain that weird behaviour at least.

**Comment by metlos** [comment]
Hi, this has been long time in the making but I believe this could have been fixed by #169 - I just released `revapi-java:0.20.1` which should have the fix.

**Comment by aldaris** [comment]
Thanks, I'll give this a go.

**Comment by aldaris** [comment]
I've upgraded revapi-java to 0.20.1, but the results remained the same. The build fails on Windows pointing at the @ versions. On OSX the build passes.

**Comment by metlos** [comment]
Ok, thanks... interesting...

**Comment by metlos** [comment]
So I've put together an integration test on the maven plugin in the https://github.com/revapi/revapi/tree/bug-173 branch. I hope it replicates what you described in this issue, but I cannot make it fail either on Linux or on Windows. Would you be able to provide a PR against that branch that would update the integration test to reproduce the issue you're seeing?

The integration test is just a maven project in https://github.com/revapi/revapi/tree/bug-173/revapi-maven-plugin/src/it/build/bug-173.

You can invoke just that integration test like this:

```
cd $REVAPI_REPO/revapi-maven-plugin
mvn verify -Dinvoker.test=bug-173
```

**Comment by aldaris** [comment]
My apologies, I've completely missed your reply. :( I'm not sure I can help diagnosing this bug any further as I no longer have access to the project that had this issue. I would suggest to close this issue as such.
