### ISSUE TITLE
Add ability to ignore revapi violations based on an annotation defined at the type level (class, interface, etc)

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#187]
See https://groups.google.com/d/msg/revapi/7kvNRWCkpKM/TtF9VSkZAQAJ

Use case:

```
@Unstable
public class XXX
{
    public void someMethodChanged()
   {
...
```

The following config will only skip reporting the breaking change if the `someMethodChanged` method is annotated with `@Unstable`. We'd also need this when the class is annotated with `@Unstable`.

```
  {
    "extension": "revapi.java.filter.annotated",
    "configuration": {
      "exclude": [
        "@org.xwiki.stability.Unstable"
      ]
    }
  },
```

Thanks

**Comment by metlos** [comment]
This should be doable with https://revapi.org/revapi-java/element-matching.html.
