### ISSUE TITLE
Need an extension to ignore violations only if an annotation is present at the type level in the previous

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#188]
Hi Lukas, we've started to use this setup:

```
  {
    // Only works at the method level for now. If the Unstable annotation is at the class level and a method has a
    // breaking change, it's not ignored. See https://github.com/revapi/revapi/issues/187
    "extension": "revapi.java.filter.annotated",
    "configuration": {
      "exclude": [
        "@org.xwiki.stability.Unstable"
      ]
    }
  },
```

However we've just realized today that it didn't work the way we wanted (for the context see https://groups.google.com/forum/#!topic/revapi/7kvNRWCkpKM) and that's it's actually quite dangerous since, for example, if we add a new method to an interface and that new method is annotated with `@Unstable`  then it's not reported as a breakage.

We need it to be reported as breakage in this case since it didn't existed before. 

What we would need is to be able to check for an annotation in the type (class, interface, etc) where the method breakage is happening and only ignore it if it's present.

This is related to https://github.com/revapi/revapi/issues/187

Right now we need to disable ignoring breaking on the `@Unstable` annotation since it's hiding real problems.

WDYT? Doable?

Thanks

**Comment by metlos** [comment]
Hmm, this is just screaming for #17 which I am 99% percent done with but I want to first finish a couple of things before I merge that huge change.

With the `element-matchers` branch merged, you could be able to express "ignore 'method added' for all methods in types annotated `@Unstable` that are not interfaces" like this:
```
match %m;

@Unstable
!interface * {
  * %m=*(**);
}
```

**Comment by metlos** [comment]
This should be possible now with revapi-maven-plugin-0.13.0 and revapi-java-0.23.0. Check out https://revapi.org/revapi-java/element-matching.html for docs.

**Comment by vmassol** [comment]
I'm currently testing with the following in revapi.json:

```
  {
    "extension": "revapi.filter",
    "configuration": {
...
        {
          "matcher": "java",
          "match": "@org.xwiki.stability.Unstable ^*;"
        }
```
