### ISSUE TITLE
Endless recursion happening during check

### ISSUE THREAD

**Issue by brandstaetter** [revapi/revapi#208]
Using maven-plugin 0.12.0 and revapi-java 0.22.0

Unfortunately I haven't had time to analyze the issue in more detail.

In my build output I get: (This breaks semantic versioning.) (This breaks semantic versioning.) (This breaks semantic versioning.) (This breaks semantic versioning.) (This breaks semantic versioning.) (This breaks semantic versioning.) ....

maybe this is hint enough? I'll try to reproduce it in more detail if I have time in the next days.

Downgrading to the previous version resolves the issue.

**Comment by metlos** [comment]
Interesting. Repro steps really would help. Or, if your code is public, just tell me how to invoke your build to repro this.

**Comment by metlos** [comment]
I was able to reproduce it.

**Comment by metlos** [comment]
Fixed in maven plugin 0.12.1. See https://revapi.org/revapi-site/news/news/20200801-regression-fix.html
