### ISSUE TITLE
feature request: In case of ambiguity allow to define in the ignore which signature you actually override

### ISSUE THREAD

**Issue by surli** [revapi/revapi#213]
Hi,

I'm currently working at refactoring an API of XWiki and I just got an interesting problem that might be become a feature of revapi in the future. For the context, you need to consider that we currently use the revapi ignores (include a justification) as part of our release process to inform about the breaking API. So the ignores are used both for checking the breaking compatibility but also as a documentation. I don't think it's exotic since the justification metadata is only here as a doc. 

So here's my problem, I'm working on refactoring a class containing the two following methods:
```
@Deprecated
public org.xwiki.ratings.AverageRatingApi getAverageRating(com.xpn.xwiki.api.Document doc)

public org.xwiki.ratings.AverageRatingApi getAverageRating(org.xwiki.model.reference.DocumentReference document)
```

And my refactoring change them for having only the following signature:
```
public java.util.Optional<org.xwiki.ratings.AverageRating> getAverageRating(org.xwiki.model.reference.EntityReference reference)
```

And right now I got the following report:
```
<item>
  <code>java.method.parameterTypeChanged</code>
  <old>parameter org.xwiki.ratings.AverageRatingApi org.xwiki.ratings.script.RatingsScriptService::getAverageRating(===com.xpn.xwiki.api.Document===)</old>
  <new>parameter java.util.Optional&lt;org.xwiki.ratings.AverageRating&gt; org.xwiki.ratings.script.AbstractScriptRatingsManager::getAverageRating(===org.xwiki.model.reference.EntityReference===) @ org.xwiki.ratings.script.RatingsScriptService</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <code>java.method.returnTypeChanged</code>
  <old>method org.xwiki.ratings.AverageRatingApi org.xwiki.ratings.script.RatingsScriptService::getAverageRating(com.xpn.xwiki.api.Document)</old>
  <new>method java.util.Optional&lt;org.xwiki.ratings.AverageRating&gt; org.xwiki.ratings.script.AbstractScriptRatingsManager::getAverageRating(org.xwiki.model.reference.EntityReference) @ org.xwiki.ratings.script.RatingsScriptService</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <code>java.method.removed</code>
  <old>method org.xwiki.ratings.AverageRatingApi org.xwiki.ratings.script.RatingsScriptService::getAverageRating(org.xwiki.model.reference.DocumentReference)</old>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
```

The problem is that I want actually to report the contrary: a change of signature of the second method and a removal of the first method (which was deprecated). 
I did try to put a ignore with the report I want to document:
```
<item>
                <code>java.method.parameterTypeChanged</code>
                <old>parameter org.xwiki.ratings.AverageRatingApi org.xwiki.ratings.script.RatingsScriptService::getAverageRating(===org.xwiki.model.reference.DocumentReference===)</old>
                <new>parameter java.util.Optional&lt;org.xwiki.ratings.AverageRating&gt; org.xwiki.ratings.script.AbstractScriptRatingsManager::getAverageRating(===org.xwiki.model.reference.EntityReference===) @ org.xwiki.ratings.script.RatingsScriptService</new>
                <justification>Redesign of Ratings API: allow to retrieve average rating for any reference (not only DocumentReference).</justification>
              </item>
              <item>
                <code>java.method.returnTypeChanged</code>
                <old>method org.xwiki.ratings.AverageRatingApi org.xwiki.ratings.script.RatingsScriptService::getAverageRating(org.xwiki.model.reference.DocumentReference)</old>
                <new>method java.util.Optional&lt;org.xwiki.ratings.AverageRating&gt; org.xwiki.ratings.script.AbstractScriptRatingsManager::getAverageRating(org.xwiki.model.reference.EntityReference) @ org.xwiki.ratings.script.RatingsScriptService</new>
                <justification>Redesign of Ratings API: use new best practices for script service return if type is nullable.</justification>
              </item>
```

but clearly it's not taken into account. It makes sense since I guess revapi doesn't match it at all right now. 
So it would nice in that kind of situation to be able to specify the actual signature we'd want to actually report for documentation purpose.

**Comment by surli** [comment]
Actually maybe in my case the `@Deprecated` annotation should be taken into account to not match the first signature but the second one. Now the problem would remain if the annotation is not there.

**Comment by surli** [comment]
> Actually maybe in my case the @Deprecated annotation should be taken into account to not match the first signature but the second one.

Actually bad idea since you usually deprecate some version before breaking. So it makes sense to match a deprecate even if the new one doesn't have it.

**Comment by surli** [comment]
I actually just got the following report on another refactoring of the same class:
```
<item>
  <code>java.method.parameterTypeChanged</code>
  <old>parameter java.util.List&lt;org.xwiki.ratings.script.RatingApi&gt; org.xwiki.ratings.script.RatingsScriptService::getRatings(===com.xpn.xwiki.api.Document===, int, int)</old>
  <new>parameter java.util.List&lt;org.xwiki.ratings.Rating&gt; org.xwiki.ratings.script.AbstractScriptRatingsManager::getRatings(===org.xwiki.model.reference.EntityReference===, int, int) @ org.xwiki.ratings.script.RatingsScriptService</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item><item>
  <code>java.method.numberOfParametersChanged</code>
  <old>method java.util.List&lt;org.xwiki.ratings.script.RatingApi&gt; org.xwiki.ratings.script.RatingsScriptService::getRatings(org.xwiki.model.reference.DocumentReference, int, int)</old>
  <new>method java.util.List&lt;org.xwiki.ratings.Rating&gt; org.xwiki.ratings.script.AbstractScriptRatingsManager::getRatings(org.xwiki.model.reference.EntityReference, int, int, boolean) @ org.xwiki.ratings.script.RatingsScriptService</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item><item>
  <code>java.method.removed</code>
  <old>method java.util.List&lt;org.xwiki.ratings.script.RatingApi&gt; org.xwiki.ratings.script.RatingsScriptService::getRatings(org.xwiki.model.reference.DocumentReference, int, int, boolean)</old>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item><item>
  <code>java.method.removed</code>
  <old>method java.util.List&lt;org.xwiki.ratings.script.RatingApi&gt; org.xwiki.ratings.script.RatingsScriptService::getRatings(com.xpn.xwiki.api.Document, int, int, boolean)</old>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
```
which feels like a bug: the second report is about a change in the number of parameters but you can see on the line below that it considers some methods with the right number of parameters as removed...

**Comment by surli** [comment]
and I also have this weird case:
```
<item>
                <code>java.method.numberOfParametersChanged</code>
                <old>method org.xwiki.ratings.script.RatingApi org.xwiki.ratings.script.RatingsScriptService::setRating(com.xpn.xwiki.api.Document, java.lang.String, int)</old>
                <new>method java.util.Optional&lt;org.xwiki.ratings.Rating&gt; org.xwiki.ratings.script.AbstractScriptRatingsManager::setRating(org.xwiki.model.reference.EntityReference, int) @ org.xwiki.ratings.script.RatingsScriptService</new>
                <justification>Redesign of Ratings API: removal of deprecated methods using Document parameter. A new API has been introduced and revapi considers it replaces it.</justification>
              </item>
              <item>
                <code>java.method.returnTypeChanged</code>
                <old>method org.xwiki.ratings.script.RatingApi org.xwiki.ratings.script.RatingsScriptService::setRating(com.xpn.xwiki.api.Document, java.lang.String, int)</old>
                <new>method java.util.Optional&lt;org.xwiki.ratings.Rating&gt; org.xwiki.ratings.script.AbstractScriptRatingsManager::setRating(org.xwiki.model.reference.EntityReference, int) @ org.xwiki.ratings.script.RatingsScriptService</new>
                <justification>Redesign of Ratings API: use new best practices for script service return if type is nullable.</justification>
              </item>
```
I should have a report for the parameter type change too IMO, not only for the change in the number of parameters.

**Comment by surli** [comment]
Sorry those last two might be real bugs, but I find they also illustrate well my need for being able to chose actually how I want to document the API change despite how revapi interprets the changes.

**Comment by metlos** [comment]
The problem here is that in the presence of method overloads, Revapi has no other option but to resort to heuristics when trying to find methods that are "most similar" and match them up for the change comparison. This of course sometimes gives results that are not completely intuitive.

If you want to change what the match criteria are, you would have to make [this beast](https://github.com/revapi/revapi/blob/master/revapi-java/src/main/java/org/revapi/java/JavaApiAnalyzer.java#L138) configurable somehow.

I would love your input on how to configure this but I personally don't see an user-friendly way of doing that. The other option is to give up on trying to match the overloads and just treat the changes as removal of old and adding of new methods.

**Comment by surli** [comment]
> I would love your input on how to configure this but I personally don't see an user-friendly way of doing that. 

Personally what I'd want is that the ignores to be used as an optional input of that method. So basically, you get and parse the ignores information given by the user first, and when you computes the changes and several overloads might correspond, you're checking first if there's already a signature given by the user matching it. Maybe it could be done in the code you sent by ordering those methods first, so they are picked first when checking against a change?

**Comment by metlos** [comment]
Since `revapi-java-0.23.0` the overload matching can be switched off, so instead of having revapi try to figure out what methods match up, you just get a bunch of removed and added methods...

see `matchOverloads` in https://revapi.org/revapi-java/configuration.html.
