### ISSUE TITLE
Incorrect warnings for deprecated extensions

### ISSUE THREAD

**Issue by nickstolwijk** [revapi/revapi#228]
I was trying to upgrade my Revapi configuration to solve the warnings for the deprected extensions `revapi.reclassify` and `revapi.ignore`, but I can't seem to get rid of the warnings.

I found https://github.com/revapi/revapi/commit/d02f019fc2b1f8c5b1ed36a85c9ab25873b5ec71 and hoped it was released already. However, I think `revapi-basic-features:0.11.3` is not yet released.

Is there a way to get rid of those warnings?

**Comment by metlos** [comment]
Unfortunately, no way of getting rid of them. I have a lot of changes piled up already and am planning a release soon but I'm not finished with some stuff that I would like to include yet. Please bear with me.
