### ISSUE TITLE
Ability to specify the artifact to compare to in a generic way a the top level POM

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#23]
It's almost possible with:

````
<oldArtifacts>
<artifact>${project.groupId}:${project.artifactId}:${project.packaging}:${xwiki.compatibility.previous.version}</artifact>
</oldArtifacts>
````

However this will fail for example if the packaging is of type "maven-archetype" (this packaging produces jar files). Right now this forces to override the config in each module having a packaging type that doesn't result in an artifact extension named after the packaging name.

**Comment by metlos** [comment]
I've added `newVersion` and `oldVersion` attributes to the config that are to be used in cases where you compare just the currently built project with its older version (which is an absolute majority of cases, IMHO). In this case specifying just the version overcomes the problems with the packaging vs. extension.

This is going to be present in `revapi-maven-plugin-0.4.4`.

**Comment by vmassol** [comment]
That's very cool, thanks!

**Comment by vmassol** [comment]
hmm I've tried it and I can't make it work.

I have:

`````
        <plugin>
          <groupId>org.revapi</groupId>
          <artifactId>revapi-maven-plugin</artifactId>
          <!-- Lock down plugin version for build reproducibility -->
          <version>0.4.3</version>
          <dependencies>
            <dependency>
              <groupId>org.revapi</groupId>
              <artifactId>revapi-java</artifactId>
              <version>0.6.3</version>
            </dependency>
          </dependencies>
          <executions>
            <execution>
              <id>revapi-check</id>
              <goals>
                <goal>check</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <oldVersion>${xwiki.compatibility.previous.version}</oldVersion>
            <skip>${xwiki.revapi.skip}</skip>
            <analysisConfiguration><![CDATA[
            {
              "revapi": {
                "filter": {
                  "elements": {
                    "exclude": [".*\\.internal\\..*", ".*\\.test\\..*"]
                  }
                }
              }
            }
            ]]></analysisConfiguration>
          </configuration>
``````

I see in https://github.com/revapi/revapi/commit/eb7d36d30157f1d57a0b5046e87c1f1014d8124a that this should work but it doesn't and when I run revapi, it says it's comparing to version 6.4.8 (it should be 8.0 since that's the value of `${xwiki.compatibility.previous.version}` (FTR I checked `mvn help:effective-pom`and it's indeed 8.0 and the config seems ok).

Any idea? Thanks

**Comment by metlos** [comment]
Have you built the maven plugin from source? I see you are using revapi-maven-plugin-0.4.3 in you snippet above, but this will be available only in 0.4.4 that I haven't released yet...

**Comment by vmassol** [comment]
oh my bad... I was using version 0.4.2 and upgraded to 0.4.3, without realizing that the change was in 0.4.4, sorry for the false alarm. Eagerly waiting for 0.4.4 to be released then :)

**Comment by metlos** [comment]
This should be present in `revapi-maven-plugin:0.4.5`.
