### ISSUE TITLE
Documentation contains broken links

### ISSUE THREAD

**Issue by m7stock** [revapi/revapi#241]
I noticed some broken links in the Revapi documentation. I am only listing them here, because I am not familiar with Antora:

- revapi-maven-plugin
  - `link:{attachmentsdir}/mail-lists.html`
  - `link:{attachmentsdir}/source-repository.html`
- several relative links that don't work anymore because of the versioning in the URL
  - `grep -Por --include=*.adoc 'link:(\.\./)+revapi.*'`

Corrections that I could do myself are in #240.

**Comment by Parthib314** [comment]
Hey @metlos, Sir can you please tell me in which repository your **mail-lists.html** file is located?
I looked at your **antora-playbook.yml** file but there every 

- source 
     *    URL: ../

So I went to the parent directory but couldn't find it there too.

**Comment by metlos** [comment]
`mail-lists.html` is most probably generated by the maven-site plugin and should end up in the `_attachments` directory of each antora module.

**Comment by Parthib314** [comment]
Sir, I think the problem is in the version of the links as for the mail-lists.html if I use --
https://revapi.org/revapi-maven-plugin/0.14.7/_attachments/mail-lists.html
 then it will not work but if
 https://revapi.org/revapi-maven-plugin/0.13.1/_attachments/mail-lists.html
this works.
And in the site when I click on the link it fetches "https://revapi.org/revapi-maven-plugin/0.14.7/_attachments/mail-lists.html"
instead of " https://revapi.org/revapi-maven-plugin/0.13.1/_attachments/mail-lists.html".

**Comment by metlos** [comment]
Ok, I see what you mean now 😄 Took me a while to understand the issue. It seems that this got broken some time between revapi-maven-plugin 0.13.2 and 0.13.3.

That said, I am not too worried about fixing the parts of the site generated by the maven site plugin. The only real usage is for generating the javadoc.

So maybe I would actually leave out all the links to mail-lists and other broken links to the (now non-existent) maven site and replace them with some alternative text. If the old site contains information not available elsewhere, I would find some place in the current antora-based site where it would fit.

For example the information about the mailing list is right at the homepage: https://revapi.org/revapi-site/main/index.html#_getting_involved

@Parthib314, would you be willing to take a look at that?

**Comment by Parthib314** [comment]
@metlos, sure sir obviously.

**Comment by Parthib314** [comment]
@metlos  can you give me any suggestions about how to change the version html files??
