### ISSUE TITLE
Versions transform configuration

### ISSUE THREAD

**Issue by npepinpe** [revapi/revapi#245]
I'm trying to configure the `revapi.versions` extension to essentially only enforce semantic versioning for binary compatibility. I've tried the following but to no avail:

```json
[
  {
    "extension": "revapi.versions",
    "configuration": {
      "enabled": true,
      "passThroughDifferences": [
        "java.class.nonPublicPartOfAPI"
      ],
      "versionIncreaseAllows": {
        "major": {
          "severity": "BREAKING"
        },
        "minor": {
          "severity": "BREAKING",
          "classification": {
            "BINARY": "NON_BREAKING",
            "SOURCE": "BREAKING",
            "SEMANTIC": "BREAKING",
            "OTHER": "BREAKING"
          }
        },
        "patch": {
          "severity": "BREAKING",
          "classification": {
            "BINARY": "NON_BREAKING",
            "SOURCE": "BREAKING",
            "SEMANTIC": "BREAKING",
            "OTHER": "BREAKING"
          }
        }
      }
    }
  }
]
```

My understanding is that `severity` needs to be the highest allowed classification, which is why I set it everywhere to `BREAKING`. Then in classification, I can hand-pick which one I want for the different levels. So for `minor`, for example, setting `BINARY` to `NON_BREAKING` but allowing everything else should guarantee that it will only break on non binary compatible changes. 

But with the following configuration, I still get transforms which are explicitly classified as non breaking reported as errors, e.g.

```
 Difference transform class org.revapi.basic.VersionsTransform transforms Difference[code='java.method.addedToInterface', name='method added to interface', classification={BINARY=NON_BREAKING, SEMANTIC=POTENTIALLY_BREAKING, SOURCE=BREAKING}, description='Method was added to an interface.', justification='null', criticality='null'] to [Difference[code='java.method.addedToInterface', name='method added to interface', classification={BINARY=NON_BREAKING, SEMANTIC=POTENTIALLY_BREAKING, SOURCE=BREAKING}, description='Method was added to an interface.', justification='null', criticality='null']]
```

I think I'm missing something. Could you explain to me why this isn't allowed? How should I configure the extension for binary compatibility only?

**Comment by npepinpe** [comment]
One thing that might help is if the debug output not only specified the classification of the difference, but what it compares it against (what's the maximum allowed), which would help figure out if the configuration isn't defined as it should be.

**Comment by npepinpe** [comment]
It seems all I was missing was adding `"regex": true` and `"code": "java\\.*"` to the configuration of each version level. Oh, and one small thing, I thought to abuse a bit the format and add a "justification" in each as a form of comment (I know, I know, would be better to use XML if I want to comment). It seems doing this will cause the configuration to silently be ignored. So the following works:

```json
[
  {
    "extension": "revapi.versions",
    "configuration": {
      "enabled": true,
      "passThroughDifferences": [
        "java.class.nonPublicPartOfAPI"
      ],
      "versionIncreaseAllows": {
        "minor": {
          "severity": "BREAKING",
          "regex": "true",
          "code": "java\\..*",
          "classification": {
            "BINARY": "NON_BREAKING",
            "SOURCE": "BREAKING",
            "SEMANTIC": "BREAKING",
            "OTHER": "BREAKING"
          }
        },
        "patch": {
          "severity": "NON_BREAKING",
          "code": "java\\..*",
          "classification": {
            "BINARY": "NON_BREAKING",
            "SOURCE": "NON_BREAKING",
            "SEMANTIC": "NON_BREAKING",
            "OTHER": "NON_BREAKING"
          }
        }
      }
    }
  }
]
```

But the following would fail with the error I posted in the initial report:

```json
[
  {
    "extension": "revapi.versions",
    "configuration": {
      "enabled": true,
      "passThroughDifferences": [
        "java.class.nonPublicPartOfAPI"
      ],
      "versionIncreaseAllows": {
        "minor": {
          "justification": "something or other",
          "severity": "BREAKING",
          "regex": "true",
          "code": "java\\..*",
          "classification": {
            "BINARY": "NON_BREAKING",
            "SOURCE": "BREAKING",
            "SEMANTIC": "BREAKING",
            "OTHER": "BREAKING"
          }
        },
        "patch": {
          "justification": "something or other",
          "severity": "NON_BREAKING",
          "code": "java\\..*",
          "classification": {
            "BINARY": "NON_BREAKING",
            "SOURCE": "NON_BREAKING",
            "SEMANTIC": "NON_BREAKING",
            "OTHER": "NON_BREAKING"
          }
        }
      }
    }
  }
]
```

Running the plugin with `-X` for debug output would still not produce any weird errors or warnings. Just FYI, it would help to know when the configuration is not being picked up :smile:

**Comment by npepinpe** [comment]
My problem is solved, by the way - but I'm leaving this up and open because I can imagine wasting time debugging issues because of misconfiguration silently being ignored :upside_down_face:

**Comment by metlos** [comment]
Ok, I think I need to work on the docs more :)

Your understanding of `severity` is correct - it looks at all the classification of compatibility types of a difference, picks the most "severe" one and compares it with the configured `severity` for given version increase. If the found severity is less or equal to the configured severity (and the version increase corresponds, too), then the difference is considered allowed.

Now, if you also specify `classification` for given version increase, then the difference must also pass the test for the classification. For each compatibility type, the severity on the difference must be the same or lower than the one configured on the version increase.

If you specify the `justification` on a version increase, then the justification on the difference must ALSO match the justification configured - that's why it didn't work for you :) If you wanted to **set** the justification on the differences that are allowed or disallowed, you should use the `onAllowed` or `onDisallowed` properties to configure that.

Lastly, given the above, I'd say the following config should work:

```json
[
  {
    "extension": "revapi.versions",
    "configuration": {
      "enabled": true,
      "passThroughDifferences": [
        "java.class.nonPublicPartOfAPI"
      ],
      "versionIncreaseAllows": {
        "major": {
          "severity": "BREAKING"
        },
        "minor": {
          "classification": {
            "BINARY": "NON_BREAKING",
            "SOURCE": "BREAKING",
            "SEMANTIC": "BREAKING",
            "OTHER": "BREAKING"
          }
        },
        "patch": {
          "classification": {
            "BINARY": "NON_BREAKING",
            "SOURCE": "BREAKING",
            "SEMANTIC": "BREAKING",
            "OTHER": "BREAKING"
          }
        }
      }
    }
  }
]
```

I have no idea why it was necessary for you to add the `regex` and  `code` to make it work - might be a bug.

Btw. to append a text to the justification of disallowed differences, you could add the following to the config:
```json
{
    "extension": "revapi.versions",
    "configuration": {
      "enabled": true,
      "onDisallowed": {
        "criticality": "error",
        "justification": {
          "append": " This breaks binary compatibility which is disallowed by the versioning policy."
        }
      },
      ...
   }
```

**Comment by npepinpe** [comment]
Thanks! You're right about code and regex, it seems to work just fine now. I'm not sure why it didn't before. We can close this :+1:
