### ISSUE TITLE
Method visibility increase can break code

### ISSUE THREAD

**Issue by metlos** [revapi/revapi#248]
When a non-final method increases visibility, it will break any overriding methods in subclasses that use the original visibility (e.g. making a protected method public will break protected overrides in subclasses). Revapi currently doesn't capture that as a special case and instead uses `java.method.visibilityIncreased` for everything.

This is surely a potential source incompatibility. Not sure if it is binary incompatible, too.

**Comment by lucifer4j** [comment]
Hi @metlos, The change of "making a protected method public will break protected overrides in subclasses" is binary compatible. [JLS 13.4.7-1](https://docs.oracle.com/javase/specs/jls/se17/html/jls-13.html#jls-13.4.7) specifically illustrates this as an example. The change is source incompatible (compilation fails) but binary compatible. Further, the text just above the example says:

>Perhaps surprisingly, the binary format is defined so that changing a member or constructor to be more accessible does not cause a linkage error when a subclass (already) defines a method to have less access.

**Comment by Parthib314** [comment]
Hey @metlos sir, Is this issue still open? I would like to work on it.

**Comment by metlos** [comment]
@Parthib314 please do, it is indeed still open. Let me know if you need any help with it..

**Comment by Parthib314** [comment]
Ok thanks, then I start working on this issue.

**Comment by Parthib314** [comment]
@metlos  sir,please check my PR
