### ISSUE TITLE
Possible false positive: Final sub-class shouldn't reveal protected type parameter from super-class

### ISSUE THREAD

**Issue by chrisvest** [revapi/revapi#251]
If we have something like the following:

```
public abstract class A<T> {
  protected T foo() { … }
}

public final class B extends A<B.E> {
  enum E {}
}
```

Revapi complains the enum `E` isn't public, but is exposed via the protected method `foo` from extending `A` with `E` as type parameter.
I argue that this isn't actually a public exposure because 1) `B` is final, and 2) it does not re-export or increase visibility of `foo`.
Thus, no class besides `B` can exist that is able to observe `foo` returning `E`. As far as I know, anyway.

**Comment by metlos** [comment]
`SocksAuthRequestDecoder` is not final so the `state()` can be called by subclasses that might not have access to `SocksAuthRequestDecoder.State`. I'd say this is valid.

Btw. I noticed that Netty defines its `UnstableApi` annotation with source retention. This means that Revapi (and japicmp, too, I believe) cannot make use of it, because it is not present in the bytecode.

**Comment by chrisvest** [comment]
> SocksAuthRequestDecoder is not final so the state() can be called by subclasses that might not have access to SocksAuthRequestDecoder.State. I'd say this is valid.

You're right about that. This applies to all the other failing examples that I found, so it looks like the change works as expected.

> Btw. I noticed that Netty defines its UnstableApi annotation with source retention.

Oh no… This opens a big can of worms. The change itself is considered incompatible, but also everything annotated with it now appears to have been removed. We'll just have to fix that in the next major release. Thanks for pointing it out.

**Comment by chrisvest** [comment]
After fixing the real cases that revapi found, I'm not running into any other problems. My build passes now, with this snapshot version.
