### ISSUE TITLE
matcher: java is there documentation, what match contains?

### ISSUE THREAD

**Issue by boaks** [revapi/revapi#258]
I followed [(see Matching and Filtering Java Elements for more info)](https://revapi.org/revapi-java/0.26.1/element-matching.html) but I still miss a more complete documentation about the content of that `match`.

```
<match>type ^* implements com.acme.Internal {}</match>
```

```
<match>@org.apiguardian.api.API(status != org.apiguardian.api.API.Status.STABLE) ^*;</match>
```

So, what is intended to be contained in the `match` element?

**Comment by metlos** [comment]
The link to [Classif](https://github.com/revapi/classif) should probably be made more prominent on that page. The readme of the Classif repo contains all the documentation there currently is...

**Comment by boaks** [comment]
Thanks!
