### ISSUE TITLE
Possibly false-positive java.class.externalClassExposedInAPI 

### ISSUE THREAD

**Issue by manuelleduc** [revapi/revapi#262]
Hello,

First thanks for the great work you are doing with revapi, this is appreciated :)

I'd like to report what's looks to me like a false positive.
I have introduced a new interface in my API (see below), and when building my project with maven I obtain the following errors:

```
ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.14.6:check (revapi-check) on project application-numbered-content-api: The following API problems caused the build to fail:
[ERROR] java.class.externalClassExposedInAPI: class com.xpn.xwiki.XWiki: A class from supplementary archives is used in a public capacity in the API. [org.xwiki.platform:xwiki-platform-oldcore:jar:13.10]
[ERROR] java.class.externalClassExposedInAPI: class com.xpn.xwiki.XWikiConfig: A class from supplementary archives is used in a public capacity in the API. [org.xwiki.platform:xwiki-platform-oldcore:jar:13.10]
[ERROR] java.class.externalClassExposedInAPI: class com.xpn.xwiki.XWikiContext: A class from supplementary archives is used in a public capacity in the API. [org.xwiki.platform:xwiki-platform-oldcore:jar:13.10]
[ERROR] java.class.externalClassExposedInAPI: class com.xpn.xwiki.XWikiException: A class from supplementary archives is used in a public capacity in the API. [org.xwiki.platform:xwiki-platform-oldcore:jar:13.10]
```

I don't understand why these errors raised. In my understanding they are false positive but they are not, I'd be happy to understand why.
Then, even when adding the xml snippet proposed with the error (see below) to my pom.xml, the error keeps being reported.

See https://github.com/manuelleduc/application-numbered-content/commit/7ed38259c3c3021527d23e140af4b74f4b39adfb for the full list of changes I did before building (in essence, adding an interface, its implementation and its use in two different places).

I'm using `revapi-maven-plugin:0.14.6`, and `revapi-java:0.26.1`.

Please let me know if you need more details.

Sincerely,
Manuel

Introduced interface:
```java
/**
 * @version $Id$
 * @since 1.2
 */
@Unstable
public interface HierarchicalConfiguration
{
    boolean resolve(XWikiDocument document, Function<XWikiDocument, Optional<Boolean>> predicate) throws Exception;
    boolean resolve(EntityReference entityReference, Function<XWikiDocument, Optional<Boolean>> predicate) throws Exception;
}
```

Proposed xml snippet:
```xml
<item>
  <ignore>true</ignore>
  <code>java.class.externalClassExposedInAPI</code>
  <new>class com.xpn.xwiki.XWiki</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.class.externalClassExposedInAPI</code>
  <new>class com.xpn.xwiki.XWikiConfig</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.class.externalClassExposedInAPI</code>
  <new>class com.xpn.xwiki.XWikiContext</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
<item>
  <ignore>true</ignore>
  <code>java.class.externalClassExposedInAPI</code>
  <new>class com.xpn.xwiki.XWikiException</new>
  <justification>ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE</justification>
</item>
```

**Comment by vmassol** [comment]
Note that when Manuel wrote this ticket he didn't know about (https://revapi.org/revapi-site/main/faq.html#_how_to_deal_with_external_class_exposed_in_api) and that we're already excluding this check for XWiki classes (see https://github.com/xwiki/xwiki-commons/blame/master/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/revapi.json#L81-L93).

Now the bug or problem seems to be that we're still getting these errors reported even though we're ignoring them.

@metlos do you see anything wrong at https://github.com/xwiki/xwiki-commons/blame/master/xwiki-commons-tools/xwiki-commons-tool-verification-resources/src/main/resources/revapi.json#L81-L93 ?

I noticed that in your example at https://revapi.org/revapi-site/main/faq.html#_how_to_deal_with_external_class_exposed_in_api you don't escape the `.`s inside the `<code>` element, whereas we do. Isn't the regex also for `<code>`?

Thx!

**Comment by metlos** [comment]
I think your use of escaped dots is ok.
But notice that the configuration uses the package regex: `com\\.xpn\\.xwiki\\..*`, whereas the package of class `com.xpn.xwiki.XWikiException` for example is `com.xpn.xwiki`. The regex only captures subpackages, not the `com.xpn.xwiki` itself. I think this should work if you changed your package regex to `com\\.xpn\\.xwiki(\\..*)?`...

**Comment by metlos** [comment]
Let me close this issue for now but please open a new one if you find any trouble with this.
