### ISSUE TITLE
Enforcing criticality

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#269]
Hi Lukas!

Would you consider adding a feature to the maven plugin to fail the build if an ignore is missing the criticality? On the XWiki project, we'd like to enforce that criticality is always set by whoever adds an ignore. If it's not done at the level of Revapi, we'll need to do it at our level, i.e. in our POM, by adding code to add an Enforcer rule.

Let us know! Thx

**Comment by metlos** [comment]
Sorry for not getting back to for such a long time. Frankly, if this is possible using an enforcer rule, I would prefer that to Revapi.

To implement it properly in Revapi, this would probably require a whole new analysis phase after transformations and before reporting and some way of configuring that.

**Comment by vmassol** [comment]
ok, thanks for the reply (thought that maybe you'd have been interested in having that feature in the revapi maven plugin).
