### ISSUE TITLE
Infinite loop in differences

### ISSUE THREAD

**Issue by uhafner** [revapi/revapi#273]
RevApi correctly found an API violation in my Jenkins Plugin: https://github.com/jenkinsci/data-tables-api-plugin/runs/6842390310?check_suite_focus=true.

In order to ignore this report I added the following snippet to my pom:
```
<revapi.differences>
               <justification>Not relevant changes that are safe to ignore</justification>
               <criticality>allowed</criticality>
               <differences>
                 <item>
                   <regex>true</regex>
                   <code>java.method.parameterTypeChanged</code>
                 </item>
               </differences>
             </revapi.differences>
```

Now RevApi produces an infinite loop:

```
[WARNING] Transformation of differences in match report Report[oldElement=parameter io.jenkins.plugins.datatables.TableConfiguration io.jenkins.plugins.datatables.TableConfiguration::select(===io.jenkins.plugins.datatables.options.SelectStyle===), newElement=parameter io.jenkins.plugins.datatables.TableConfiguration io.jenkins.plugins.datatables.TableConfiguration::select(===io.jenkins.plugins.datatables.TableConfiguration.SelectStyle===), problems=[Difference[code='java.method.parameterTypeChanged', name='parameter type changed', classification={SOURCE=POTENTIALLY_BREAKING, BINARY=BREAKING}, description='The type of the parameter changed from 'io.jenkins.plugins.datatables.options.SelectStyle' to 'io.jenkins.plugins.datatables.TableConfiguration.SelectStyle'.', justification='Not relevant changes that are safe to ignore', criticality='Criticality[name='error', level=2147483647]'], Difference[code='java.method.parameterTypeChanged', name='parameter type changed', classification={SOURCE=POTENTIALLY_BREAKING, BINARY=BREAKING}, description='The type of the parameter changed from 'io.jenkins.plugins.datatables.options.SelectStyle' to 'io.jenkins.plugins.datatables.TableConfiguration.SelectStyle'.', justification='null', criticality='Criticality[name='error', level=2147483647]']]] has cycled 381000 times. Maybe we're in an infinite loop with differences transforming back and forth?
```

See https://github.com/jenkinsci/data-tables-api-plugin/pull/288 for details.

**Comment by metlos** [comment]
Huh, turns out the default configuration of `revapi.versions` sets the criticality to `error` on disallowed changes and you're setting the criticality to `allowed` on the subset of those changes. `revapi.versions` and `revapi.differences` therefore "fight" over who
is right and that results in the infinite loop.

Luckily there's a solution to that using transformation blocks for which there actually even is an example in the docs: https://revapi.org/revapi-basic-features/0.12.5/versions.html#_allow_changes_that_are_marked_as_ok_by_other_rules

**Comment by metlos** [comment]
I think in your case, it might actually be enough to just put the `revapi.differences` after `revapi.versions` in the pipeline configuration, but you can get an idea about a more fine-grained approach from the example.
