### ISSUE TITLE
Potential NullPointerException in ClasspathScanner$Scanner

### ISSUE THREAD

**Issue by alzimmermsft** [revapi/revapi#280]
Using a custom `TreeFilterProvider` as the only filter in the RevApi pipeline I'm hitting a `NullPointerException` in `ClasspathScanner$Scanner` where it appears that the parent element didn't exist yet in the `types` cache.

Attempt to add the current element as a child element in the `TypeRecord` is where the `NullPointerException` exception is being thrown from: https://github.com/revapi/revapi/blob/main/revapi-java/src/main/java/org/revapi/java/compilation/ClasspathScanner.java#L457

Based on this exception and the code path it appears that the parent `TypeRecord` doesn't exist in the `types` cache being maintained by `ClasspathScanner`: https://github.com/revapi/revapi/blob/main/revapi-java/src/main/java/org/revapi/java/compilation/ClasspathScanner.java#L725

The is the pipeline configuration for `TreeFilterProvider` inclusion:

```xml
<filters>
  <include>
    <item>azure-sdk-tree-provider</item>
  </include>
</filters>
```

And this is the custom `TreeFilterProvider` being used (active WIP): https://github.com/Azure/azure-sdk-for-java/blob/e9c14ae16e1e7fbc26a1b4fdff9e3239299b84f3/eng/code-quality-reports/src/main/java/com/azure/tools/revapi/transforms/AzureSdkTreeFilterProvider.java

This interface is one of the cases where the `NullPointerException` is being thrown: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/confluent/azure-resourcemanager-confluent/src/main/java/com/azure/resourcemanager/confluent/models/OrganizationResource.java#L136

**Comment by alzimmermsft** [comment]
Dug around a bit more and this may be how the `JavaFileObject`s are iterated here: https://github.com/revapi/revapi/blob/main/revapi-java/src/main/java/org/revapi/java/compilation/ClasspathScanner.java#L402

I looked at the JAR/ZIP file generated by RevApi in local temporary AppData (in Windows) and it appears it's iterating the JAR/ZIP by the offset in reverse order which results in interfaces contained in other interfaces being processed before the containing interface, resulting in the `TypeRecord` not existing.

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/48699787/214074437-ae3f8951-d3ff-4e66-b94b-d10362d54dd3.png">

**Comment by alzimmermsft** [comment]
Should also add Java version information:

openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

**Comment by alzimmermsft** [comment]
@metlos I checked and this appears to be an issue when there is a class nested in a nested class, something like

``` java
class A {
  class B {
    class C {
    }
  }
}
```

It appears the issue is that if `Class A` will be filtered out but `Class C` is the first to be processed the checking done [here](https://github.com/revapi/revapi/blob/main/revapi-java/src/main/java/org/revapi/java/compilation/ClasspathScanner.java#L426) will traverse to `Class B` realize it wasn't processed then during that traverse to `Class A` and realize that wasn't processed as well. From there `Class A` will fully be processed and be filtered out to not be included in the processing tree, it'll return from the recursive call and here `Class B` will check its enclosing `TypeRecord` (`Class A` in this case) for being included, since it's not included it'll early out on the recursion. Now we're back to `Class C`, it'll check its enclosing `TypeRecord` (`Class B` now) for inclusion but since `Class B` was never fully scanned the inclusion is undefined. This then causes `Class C` to no early out and continue processing, subsequently resulting in `Class C` throwing a `NullPointerException`.

Now in this reality this doesn't matter as `Class C` won't be processed correctly but it would have been ignored anyways. But this noise leaves less confidence in the results given the exception being thrown and the message about results may not be complete.

Is this an issue in the design of the filter I have or am I just seeing a processing order change?

**Comment by metlos** [comment]
I'm not able to look at this closer until the next week, but the analysis you did so far is outstanding. ClasspathScanner is the hairiest part of the codebase but the undecided following results should be supported because they can turn up in other situations than just "unfortunate"order of evaluation of classes (some more complex java filters that reference several classes can easily trigger this, too).

So this is definitely a bug that needs to be fixed.

Again, thanks for your work so far, this helps tremendously.

**Comment by alzimmermsft** [comment]
I did create a small prototype when I had `ClasspathScanner` natural order sort the class files by name before running analysis, I can open a PR for that if you think that would be a good way to handle this. I believe I even came across a comment which mentioned this issue of out-of-order processing.
