### ISSUE TITLE
Plugin breaks in Maven4

### ISSUE THREAD

**Issue by cstamas** [revapi/revapi#292]
Plugin violates Maven Resolver API expectations:
https://maven.apache.org/resolver/api-compatibility.html

It uses class `org.eclipse.aether.impl.UpdateCheck.getPolicy()` that according to doco above does NOT guarantee binary compatibility.

Given you are interested in string label of the update policy, it makes more sense to get it from Maven settings or alike instead.

Error reported when Mojo executes:
```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.15.0:check (default) on project <EDITED>: Execution default of goal org.revapi:revapi-maven-plugin:0.15.0:check failed: An API incompatibility was encountered while executing org.revapi:revapi-maven-plugin:0.15.0:check: java.lang.NoSuchMethodError: 'java.lang.String org.eclipse.aether.impl.UpdateCheck.getPolicy()'
```

**Comment by metlos** [comment]
Would you be able to provide the stack trace leading to that error? I don't see any direct usage of that method.

**Comment by cstamas** [comment]
Sorry, you are right. The cause is NOT this plugin, but a build extension.... Sorry for the noise and closing this out.
