### ISSUE TITLE
Plan for native gradle plugin?

### ISSUE THREAD

**Issue by ajantha-bhat** [revapi/revapi#296]
External gradle plugin is not actively maintained (https://github.com/revapi/revapi?tab=readme-ov-file#gradle) and the same plugin doesn't work with the latest gradle version (https://github.com/palantir/gradle-revapi/issues/612)

So, is it possible to have a gradle plugin maintained and released as part of this community?

**Comment by ajantha-bhat** [comment]
cc: @CRogers

**Comment by ajantha-bhat** [comment]
ping

**Comment by metlos** [comment]
No plans to maintain it myself. If you're willing to take it up I'd be happy to help out with setting up the infrastructure (e.g. repo under the revapi org) and answer any questions you might have when implementing it...

**Comment by ajantha-bhat** [comment]
Thanks for the reply. I would like to know if @CRogers wants to contribute their repo to this project. That way we don't have to reinvent the wheel. 

My idea was to maintain and fix bugs on top of it.

**Comment by CRogers** [comment]
palantir/gradle-revapi is under the Apache license - feel free to fork or copy it and make an official version if you wish. I'd certainly like to migrate to an official version if we could and avoid maintaining our plugin. 

Our plugin is not Gradle 8 compatible yet as we havent got to it yet - we have an large number of plugins in the queue for addinv Gradle 8 support (with a pretty lean team) and this one is quite far down the list due to limited internal use. We will eventually upgrade it. I will say that this was the first real Gradle plugin I ever made from scratch - it could definitely be improved (particularly the bit that find jar outputs - which is iirc is what's going wrong in Gradle 8).

**Comment by ajantha-bhat** [comment]
cc:@jbonofre, @Fokko, @nastra

**Comment by jbonofre** [comment]
We already fork the gradle revapi plugin and I fixed the gradle 8.2+ support. Happy to bring it here and maintain it if we have a consensus.

**Comment by ajantha-bhat** [comment]
we should fork `https://github.com/palantir/gradle-revapi` and keep new commits on top of it IMO and make a new release.

**Comment by metlos** [comment]
Ok, moving quickly I forked https://github.com/palantir/gradle-revapi and made you @ajantha-bhat the maintainer of it. We can keep this issue open to discuss any other setup needed, like how to do releases, etc, or, in fact, if you even want to be the person maintaining it 😉

**Comment by metlos** [comment]
The repo is https://github.com/revapi/gradle-revapi

**Comment by ajantha-bhat** [comment]
Thanks. Please also invite @jbonofre, @Fokko, @nastra, @CRogers

**Comment by ajantha-bhat** [comment]
The next plan is to cherrypick the gradle update and plugin fix PRs to this repo and do a release.

**Comment by nastra** [comment]
I'll look into this tomorrow and will cherry-pick the required commits to update the plugin so that it works with the latest Gradle version (since I've done that already in my fork)

**Comment by jbonofre** [comment]
I think we need:
- cleanup/rename of the original plugin to match revapi "hosting"
- update to Gradle 8 (and other dependencies), maybe cleanup some dependency gradles
- fix  on Gradle 8.2+ by using `externalConfiguration`

Ready to help there 😄

**Comment by metlos** [comment]
@ajantha-bhat is the maintainer and @jbonofre, @Fokko, @nastra and @CRogers have write access to the repository. Let's make some history 😄 ![pic](https://github.com/revapi/revapi/assets/19999/424847ea-df0c-4358-a61e-78233b23bd78)

**Comment by ajantha-bhat** [comment]
@metlos: We wanted to enable `issues` tab. So, the users can reprot issues or use for tracking tasks. 

Do you know why it is missing for this repo? Even as a maintainer, I can't see it in features. Only Admin can enable it?
<img width="1515" alt="image" src="https://github.com/revapi/revapi/assets/5889404/aaa76ff8-37ab-4229-96cb-a2e58efb4865">

So, please enable it.

**Comment by nastra** [comment]
@metlos thanks for adding us. I've opened https://github.com/revapi/gradle-revapi/pull/1 to get the plugin working with the latest Gradle version. Next I'd like to rename the plugin from `com.palantir.revapi` to something else. Any suggestions in terms of plugin naming? I was thinking something along the lines of `io.github.revapi.gradle-revapi`

**Comment by ajantha-bhat** [comment]
> Any suggestions in terms of plugin naming? I was thinking something along the lines of io.github.revapi.gradle-revapi

I think we should have it as `org.revapi.revapi-gradle-plugin` similar naming as maven plugin
https://revapi.org/revapi-maven-plugin/0.15.0/index.html#_examples

**Comment by nastra** [comment]
Makes sense, I've updated this to `org.revapi.revapi-gradle-plugin`

**Comment by ajantha-bhat** [comment]
@metlos: The `main` branch is ready for 1.8.0 release. It has all the required fixes. 

cc: @nastra, @jbonofre

**Comment by nastra** [comment]
I can take care of doing the Initial Plugin Release since I went through the process already when releasing the forked plugin

**Comment by nastra** [comment]
I can take care of doing the Initial Plugin Release since I went through the process already when releasing the forked plugin

**Comment by nastra** [comment]
@metlos I've submitted the plugin and it's currently awaiting approval from Gradle to be released (which takes a few days). Can you please follow https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html#account_setup and create an account for the revapi org. I currently used my own Gradle plugin credentials for publishing but we can transfer the plugin to the revapi org (as described in https://github.com/gradle/plugin-portal-requests) so that revapi shows up as the plugin owner.

**Comment by nastra** [comment]
@metlos I've opened https://github.com/revapi/gradle-revapi/pull/6. The one thing left that we need is to have GitHub secrets named `GRADLE_KEY` / `GRADLE_SECRET` in the https://github.com/revapi/gradle-revapi repo containing the info from that Revapi Org account I mentioned in my previous comment.

**Comment by ajantha-bhat** [comment]
@metlos: Hi, it seems the gradle publish is blocked because they want us to publish using the official rev api account (created using  https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html#account_setup). 

Shall I use my email and create an account by 'rev api' or do you have an official email that you use and you want to create the account using that?

**Comment by ajantha-bhat** [comment]
I went ahead and created the user under the name revAPI
https://plugins.gradle.org/u/revapi

**Comment by metlos** [comment]
Thanks @ajantha-bhat and sorry for the slower response times. To make up for it, I enabled the issues in `revapi/gradle-revapi`.

**Comment by ajantha-bhat** [comment]
Thanks @metlos: I have submitted the plugin (it is based on 1.8.0 tag)
<img width="1465" alt="image" src="https://github.com/revapi/revapi/assets/5889404/e99d440a-6c13-4edc-89ef-6585ac33322b">

Once, it is approved, we can announce the release.

**Comment by ajantha-bhat** [comment]
hi @metlos, the plugin submission has failed 😢 
They are asking me to prove `revapi.org` domain ownership by adding some text to DNS or use official rev api email id.  

I don't have your email to discuss this privately. Please send me an email (ajanthabhat@gmail.com) to discuss more about it. Thanks.

**Comment by metlos** [comment]
@ajantha-bhat email sent

**Comment by ajantha-bhat** [comment]
Official plugin has been released 🎉 

https://github.com/revapi/gradle-revapi/releases

Thanks everyone.
