### ISSUE TITLE
visibility reduced in a private class

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#30]
This looks strange. when running revapi this morning I get:

`````
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.4.3:check (revapi-check) on project xwiki-commons-logging-api: The following API problems caused the build to fail:
[ERROR] [org.xwiki.commons:xwiki-commons-logging-api:jar:8.1-SNAPSHOT] method void org.xwiki.logging.LogTreeNode.LogTreeNodeIterator::<init>(java.util.Iterator<org.xwiki.logging.event.LogEvent>): java.method.visibilityReduced: visibility reduced
[ERROR] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:
[ERROR] {
[ERROR] "code": "java.method.visibilityReduced",
[ERROR] "old": "method void org.xwiki.logging.LogTreeNode.LogTreeNodeIterator::<init>(java.util.Iterator<org.xwiki.logging.event.LogEvent>)",
[ERROR] "new": "method void org.xwiki.logging.LogTreeNode.LogTreeNodeIterator::<init>(java.util.Iterator<org.xwiki.logging.event.LogEvent>)",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] }
`````

Indeed the visibility has been reduced from "public" to package: https://github.com/xwiki/xwiki-commons/commit/8c60c7c83bfd443e613e2371129d2b86a0f67047#diff-6bc94a3a8724b43ea7df8982ad8b13afL46

However this class where it happened is private: https://github.com/xwiki/xwiki-commons/blob/8c60c7c83bfd443e613e2371129d2b86a0f67047/xwiki-commons-core/xwiki-commons-logging/xwiki-commons-logging-api/src/main/java/org/xwiki/logging/LogTreeNode.java#L40

Could you confirm that this is a bug? Thanks

**Comment by metlos** [comment]
This is most probably a bug. It might be that revapi determined that that private class is used publicly (i.e. you have it as a return type or method parameter of some public method), but if that was the case, you'd get a problem description for that case, too.

**Comment by metlos** [comment]
Accessibility resolution has its problems, see #10. I've been working more on the usability enhancements lately but I need to get back to #10 and your new finding, too, and fix it for good.

**Comment by vmassol** [comment]
ah ok, sorry for the duplicate.

**Comment by metlos** [comment]
this is not really a duplicate, but rather another occurrence of a deeper problem with how revapi resolves the accessibility of elements. I'm hoping this will be solved together with #10 but we'll see...

**Comment by metlos** [comment]
This will be fixed in `revapi-java-0.6.4`.

**Comment by vmassol** [comment]
Thanks Lukas!

**Comment by metlos** [comment]
This should be fixed in `revapi-0.7.0` that's been just released.

**Comment by vmassol** [comment]
Hi Lukas, just updated to 0.7.0 and got several problems in xwiki-commons-job:

`````
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.4.5:check (revapi-check) on project xwiki-commons-job: The following API problems caused the build to fail:
[ERROR] java.class.nowCheckedException: class com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.DuplicateFieldException: Throwable class is now a checked exception.[com.thoughtworks.xstream:xstream:jar:1.4.8]
[ERROR] java.class.nowCheckedException: class com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.UnknownFieldException: Throwable class is now a checked exception.[com.thoughtworks.xstream:xstream:jar:1.4.8]
[ERROR] java.class.nowCheckedException: class com.thoughtworks.xstream.core.AbstractReferenceMarshaller.ReferencedImplicitElementException: Throwable class is now a checked exception.[com.thoughtworks.xstream:xstream:jar:1.4.8]
[ERROR] java.class.nowCheckedException: class com.thoughtworks.xstream.core.TreeMarshaller.CircularReferenceException: Throwable class is now a checked exception.[com.thoughtworks.xstream:xstream:jar:1.4.8]
[ERROR] 
[ERROR] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:
[ERROR] {
[ERROR] "code": "java.class.nowCheckedException",
[ERROR] "old": "class com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.DuplicateFieldException",
[ERROR] "new": "class com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.DuplicateFieldException",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] },
[ERROR] {
[ERROR] "code": "java.class.nowCheckedException",
[ERROR] "old": "class com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.UnknownFieldException",
[ERROR] "new": "class com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.UnknownFieldException",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] },
[ERROR] {
[ERROR] "code": "java.class.nowCheckedException",
[ERROR] "old": "class com.thoughtworks.xstream.core.AbstractReferenceMarshaller.ReferencedImplicitElementException",
[ERROR] "new": "class com.thoughtworks.xstream.core.AbstractReferenceMarshaller.ReferencedImplicitElementException",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] },
[ERROR] {
[ERROR] "code": "java.class.nowCheckedException",
[ERROR] "old": "class com.thoughtworks.xstream.core.TreeMarshaller.CircularReferenceException",
[ERROR] "new": "class com.thoughtworks.xstream.core.TreeMarshaller.CircularReferenceException",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] }
[ERROR] -> [Help 1]
`````

I'm not sure why suddenly revapi is checking third-paty deps by default. Is there also a way to turn this off? Thanks

**Comment by metlos** [comment]
Hmm...

The reason you didn't get this exception before was because the usage tracking of super classes was broken leading to problems with establishing the visibility of for example public methods in private superclasses.

The reason for getting these breakages is  that `org.xwiki.job.internal.xstream.SafeReflectionConverter` inherits from `com.thoughtworks.xstream.converters.reflection.ReflectionConverter` which "drags" the `DuplicateFieldException` and  `UnknownFieldException` into xwiki's API (i.e. you can say `SafeReflectionConverter.DuplicateException`).
The marshaller exceptions are dragged into the API like this: `org.xwiki.job.internal.xstream.SafeTreeMarshallingStrategy::createMarshallingContext` method returns a `com.thoughtworks.xstream.core.TreeMarshaller` which makes the `ReferencedImplicitElementException` and `CircularReferenceException` accessible to the callers of the `createMarshallingContext` method.

You have an exclude for the internal classes but this is only applied after the API "tree" is established (and therefore `com.thoughtworks...` classes determined to be part of the API). So effectively, you exclude the `SafeReflectionConverter` and `SafeTreeMarshallingStrategy` from the API check but revapi is currently not smart enough to realize that all other classes that they "dragged" into the API, should be excluded as well (if they are not used otherwise on other places).

You could work around this by modifying the includes/excludes like this:

```javascript
{
  "revapi": {
    "java": {
      "filter": {
        "packages": {
          "include": ["org\\.xwiki\\..*"],
          "exclude": ["org\\.xwiki\\..*\\.internal\\..*", "org\\.xwiki\\..*\\.test\\..*"]
        }
      }
    }
  }
}
```

I.e. you only consider classes from packages starting with `org.xwiki` and from them you exclude the `internal` and `test` packages and their sub-packages.

**Comment by vmassol** [comment]
Thanks for the reply Lukas. However this workaround has an important drawback since we can also extend non-xwiki classes in our non-internal XWiki classes and by checking only classes in the `org.xwiki` package we're going to miss real backward incompatibilities.

**Comment by metlos** [comment]
Oh, the exclude should probably be:
```javascript
["org\\.xwiki\\..*\\.internal(\\..*)?", "org\\.xwiki\\..*\\.test(\\..*)?"]
```
to also exclude the `internal` and `test` packages themselves.

**Comment by metlos** [comment]
Yep, that is true. Could you please raise a new issue for this problem and I will see what I can do about it.

**Comment by vmassol** [comment]
Done at https://github.com/revapi/revapi/issues/35 thanks

**Comment by vmassol** [comment]
BTW I tried your include/exclude and it didn't work. I got the same error as before.

**Comment by metlos** [comment]
I tried it, too, and it did work :-)

The thing is that xwiki-commons-core/pom.xml redefines the config, so you need to make sure that you include your changes there or directly at the job pom. Due to the unfortunate fact of noninheritable json config, it is not enough to define the excludes at the root pom of xwiki-commons. 

The XML config is the very next thing I'm going to work on, once we stabilize your setup of xwiki.

30. března 2016 19:29:29 CEST, Vincent Massol <notifications@github.com> napsal:

**Comment by vmassol** [comment]
Yes I know about the issue with overriding the configuration. `mvn help:effective-pom` at the level of `xwiki-commons-job` gives me this:

`````
      <plugin>
        <groupId>org.revapi</groupId>
        <artifactId>revapi-maven-plugin</artifactId>
        <version>0.4.5</version>
        <executions>
          <execution>
            <id>revapi-check</id>
            <goals>
              <goal>check</goal>
            </goals>
            <configuration>
              <analysisConfiguration>{
              "revapi": {
                "filter": {
                  "packages": {
                    "include": ["org\\.xwiki\\..*"],
                    "exclude": ["org\\.xwiki\\..*\\.internal(\\..*)?", "org\\.xwiki\\..*\\.test(\\..*)?"]
                  }
                },
                "ignore": [
                ]
              }
            }</analysisConfiguration>
              <oldVersion>8.0</oldVersion>
              <skip>false</skip>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.revapi</groupId>
            <artifactId>revapi-java</artifactId>
            <version>0.7.0</version>
            <scope>compile</scope>
          </dependency>
        </dependencies>
        <configuration>
          <analysisConfiguration>{
              "revapi": {
                "filter": {
                  "packages": {
                    "include": ["org\\.xwiki\\..*"],
                    "exclude": ["org\\.xwiki\\..*\\.internal(\\..*)?", "org\\.xwiki\\..*\\.test(\\..*)?"]
                  }
                },
                "ignore": [
                ]
              }
            }</analysisConfiguration>
          <oldVersion>8.0</oldVersion>
          <skip>false</skip>
        </configuration>
      </plugin>
````

It looks ok to me. Can you see what's wrong? Thanks

**Comment by metlos** [comment]
yep, it's `revapi.java.filter.packages`, not `revapi.filter.packages`. This is the consequence of the modular nature of revapi - revapi.filter is dedicated to the generic filtering mechanism that works on textual representations of elements, while revapi.java.filter is for filtering using java-specific means.

**Comment by vmassol** [comment]
haha thanks for spotting this!
