### ISSUE TITLE
Get a summary of errors by default

### ISSUE THREAD

**Issue by tmortagne** [revapi/revapi#32]
It sure is nice to have all those detailed information you can just copy/paste when all you want is ignore whatever errors you have but when you actually want to know what those errors are my feeling is that I have to spend more time than I should to extract the actual information in the middle of a bunch of noise. It would be nice to have just the actual issue without detailed documentation around by default (and enable the detail with some system/pom property or something).

I come from CLIRR which I found more readable. Here is an example for the same errors (3 errors very easy to fix in Java 8 that I don't want to put in the ignored errors):

CLIRR:

```
[ERROR] 7012: org.xwiki.extension.job.ExtensionRequest: Method 'public boolean isRootModificationsAllowed()' has been added to an interface
[ERROR] 7012: org.xwiki.extension.ExtensionDependency: Method 'public boolean isCompatible(org.xwiki.extension.ExtensionId)' has been added to an interface
[ERROR] 7012: org.xwiki.extension.ExtensionDependency: Method 'public boolean isCompatible(org.xwiki.extension.Extension)' has been added to an interface
```

revapi:

```
[ERROR] [org.xwiki.commons:xwiki-commons-extension-api:jar:8.1-SNAPSHOT] method boolean org.xwiki.extension.ExtensionDependency::isCompatible(org.xwiki.extension.Extension): java.method.addedToInterface: Method was added to an interface.
[ERROR] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:
[ERROR] {
[ERROR] "code": "java.method.addedToInterface",
[ERROR] "new": "method boolean org.xwiki.extension.ExtensionDependency::isCompatible(org.xwiki.extension.Extension)",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] }
[ERROR] [org.xwiki.commons:xwiki-commons-extension-api:jar:8.1-SNAPSHOT] method boolean org.xwiki.extension.ExtensionDependency::isCompatible(org.xwiki.extension.ExtensionId): java.method.addedToInterface: Method was added to an interface.
[ERROR] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:
[ERROR] {
[ERROR] "code": "java.method.addedToInterface",
[ERROR] "new": "method boolean org.xwiki.extension.ExtensionDependency::isCompatible(org.xwiki.extension.ExtensionId)",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] }
[ERROR] [org.xwiki.commons:xwiki-commons-extension-api:jar:8.1-SNAPSHOT] method boolean org.xwiki.extension.job.ExtensionRequest::isRootModificationsAllowed(): java.method.addedToInterface: Method was added to an interface.
[ERROR] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:
[ERROR] {
[ERROR] "code": "java.method.addedToInterface",
[ERROR] "new": "method boolean org.xwiki.extension.job.ExtensionRequest::isRootModificationsAllowed()",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] }
```

several errors like this really makes it quite a pain to extract the actual breakages from the huge error block

**Comment by metlos** [comment]
The info in the log is for the times when you develop your code and revapi finds that you broke something.

I would argue that in the majority of the cases you actually want revapi to either ignore your change because you made it consciously or you want to modify your changes so that they don't break the API.

I think that "see what the changes actually are" is relatively minor usecase, for which there actually is a goal: `report` ;)

If you issue `mvn package revapi:report` you'll get a site page with all the changes detailed in a table.

Also, upcoming in `revapi-reporting-text:0.5.0` you'll get the ability to output the found differences in whatever format you want using FreeMarker templates (see 4eb43fb73e0be7e35f577853d22ba90f4e6a7ac1).

What could be done here though is to reduce the noise in this way:
```
[ERROR] [org.xwiki.commons:xwiki-commons-extension-api:jar:8.1-SNAPSHOT] method boolean org.xwiki.extension.ExtensionDependency::isCompatible(org.xwiki.extension.Extension): java.method.addedToInterface: Method was added to an interface.
[ERROR] [org.xwiki.commons:xwiki-commons-extension-api:jar:8.1-SNAPSHOT] method boolean org.xwiki.extension.ExtensionDependency::isCompatible(org.xwiki.extension.ExtensionId): java.method.addedToInterface: Method was added to an interface.
[ERROR] [org.xwiki.commons:xwiki-commons-extension-api:jar:8.1-SNAPSHOT] method boolean org.xwiki.extension.job.ExtensionRequest::isRootModificationsAllowed(): java.method.addedToInterface: Method was added to an interface.
[ERROR] If you're using the semver-ignore extension, update your module's version to one compatible with the current changes (e.g. mvn package revapi:update-versions). If you want to explicitly ignore this change and provide a justification for it, add the following JSON snippet to your Revapi configuration under "revapi.ignore" path:
[ERROR] {
[ERROR] "code": "java.method.addedToInterface",
[ERROR] "new": "method boolean org.xwiki.extension.ExtensionDependency::isCompatible(org.xwiki.extension.Extension)",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] },
[ERROR] {
[ERROR] "code": "java.method.addedToInterface",
[ERROR] "new": "method boolean org.xwiki.extension.ExtensionDependency::isCompatible(org.xwiki.extension.ExtensionId)",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] },
[ERROR] {
[ERROR] "code": "java.method.addedToInterface",
[ERROR] "new": "method boolean org.xwiki.extension.job.ExtensionRequest::isRootModificationsAllowed()",
[ERROR] "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
[ERROR] }
```

Would that help you?

**Comment by metlos** [comment]
Also, I'm working on #29 (for which 4eb43fb73e0be7e35f577853d22ba90f4e6a7ac1 is a first step) that would give you similar overview build-wide, not just module-wide.

**Comment by tmortagne** [comment]
> Would that help you?

It's a lot nicer yes. Also nicer for "the lets ignore everything" use case since it's only one block to copy/paste in this version so everyone is happy :)

Note: I don't think repeating the module ("org.xwiki.commons:xwiki-commons-extension-api:jar:8.1-SNAPSHOT") is very useful since you already have this information in the Maven build.

**Comment by metlos** [comment]
> Note: I don't think repeating the module ("org.xwiki.commons:xwiki-commons-extension-api:jar:8.1-SNAPSHOT") is very useful since you already have this information in the Maven build.

The thing is that if the API change happened in one of your dependencies, you'd see the GAV of that dependency there instead of the GAV of your module. This would happen if you updated your dep to a new version that broke the API and the type in question was somehow referenced by the API of your module. I.e. your class would inherit from a class in a dep or you used a class from your dep as a return type or method param or a type of accessible field.

Maybe we could put that info at the end of the line instead of the start or even output it only if the artifact the change is coming from is not from the "primary" API.

**Comment by tmortagne** [comment]
> even output it only if the artifact the change is coming from is not from the "primary" API

+1

**Comment by metlos** [comment]
This will be in `revapi-maven-plugin:0.4.4`.

**Comment by tmortagne** [comment]
Thanks !

**Comment by metlos** [comment]
`revapi-maven-plugin:0.4.5` has been released with this fix.
