### ISSUE TITLE
Support multiple configurations per extension

### ISSUE THREAD

**Issue by metlos** [revapi/revapi#34]
or rather multiple differently configured extensions of the same type in a single analysis run.

This should be helpful in cases where people would like to for example have multiple differently configured outputs.

Maven plugin could then learn to exclude certain configurations which could provide a way to implement the suggestions of @vmassol in https://github.com/revapi/revapi/issues/29#issuecomment-200337747 without resorting to hacks like masking subsets of extension-specific configuration (by having their ignores split into multiple configurations and then picking and choosing some of them however they wish).

This should probably be implemented together with #19.

**Comment by vmassol** [comment]
Hi Lukas, I'm looking forward to upgrading our revapi version for XWiki and I was looking for the changelog/release notes to know what has changed from our version to the latest one. Does that exist? How can I find out the changes brought? Thanks!

**Comment by metlos** [comment]
Hi, yeah... I got distracted and never sent out the email to the mailing list... Hopefully I will get to it in the evening...

**Comment by vmassol** [comment]
ah ok so it's a mail on the list. I was looking for a page on revapi.org actually :)

**Comment by vmassol** [comment]
FTR I'm now trying to use the feature from this issue to share the config. Thanks for implementing it ! :)

**Comment by metlos** [comment]
Yeah, news on the site is another thing on the todo list ;)
