### ISSUE TITLE
No violation reported for method added to interface

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#36]
This is strange and I don't know if it's me doing something wrong or not.

Basically I modified the [URLNormalizer](https://github.com/xwiki/xwiki-platform/blob/e49d585ed97a82a1d7b8a3bbcda7f4dff4773c00/xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-api/src/main/java/org/xwiki/url/URLNormalizer.java#L47-L47) interface to add a new method in order to generate a violation but running `mvn clean verify -DskipTests=true`in `xwiki-platform/xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-api`gives:

`````
[INFO] --- revapi-maven-plugin:0.4.5:check (revapi-check) @ xwiki-platform-url-api ---
[INFO] Comparing [org.xwiki.platform:xwiki-platform-url-api:jar:8.0] against [org.xwiki.platform:xwiki-platform-url-api:jar:8.1-SNAPSHOT] (including their transitive dependencies).
[INFO] API checks completed without failures.
`````

What's even stranger is that running `mvn clean verify  -DskipTests=true -Dxwiki.compatibility.previous.version=6.0`(i.e comparing to a very old version) also gives no errors.

Any idea?

Thanks

**Comment by metlos** [comment]
What branch is the change on?

Looking https://github.com/xwiki/xwiki-platform/commits/e49d585ed97a82a1d7b8a3bbcda7f4dff4773c00/xwiki-platform-core/xwiki-platform-url/xwiki-platform-url-api/src/main/java/org/xwiki/url/URLNormalizer.java I see the last change on Christmas Eve last year...

**Comment by vmassol** [comment]
> What branch is the change on?

master

**Comment by metlos** [comment]
thanks, I see it now... the new method is even in the debug output of revapi (mvn ... -X)... wth is going on :-\

**Comment by vmassol** [comment]
FTR I have the same issue in `xwiki-commons`, if you check `xwiki-commons/xwiki-commons-core` you'll see some revapi ignore:

````
                "ignore": [
                  {
                    "code": "java.method.returnTypeTypeParametersChanged",
                    "old": "method java.util.List<? extends org.xwiki.extension.ExtensionDependency> org.xwiki.extension.AbstractExtension::getDependencies()",
                    "new": "method java.util.List<org.xwiki.extension.ExtensionDependency> org.xwiki.extension.AbstractExtension::getDependencies()",
                    "justification": "? return type makes signature more complex for nothing"
                  },
                  {
                    "code": "java.method.returnTypeTypeParametersChanged",
                    "old": "method java.util.Collection<? extends org.xwiki.extension.ExtensionDependency> org.xwiki.extension.Extension::getDependencies()",
                    "new": "method java.util.Collection<org.xwiki.extension.ExtensionDependency> org.xwiki.extension.Extension::getDependencies()",
                    "justification": "? return type makes signature more complex for nothing"
                  },
                  {
                    "code": "java.method.returnTypeTypeParametersChanged",
                    "old": "method java.util.Collection<? extends org.xwiki.extension.ExtensionDependency> org.xwiki.extension.wrap.WrappingExtension<E extends org.xwiki.extension.Extension>::getDependencies()",
                    "new": "method java.util.Collection<org.xwiki.extension.ExtensionDependency> org.xwiki.extension.wrap.WrappingExtension<E extends org.xwiki.extension.Extension>::getDependencies()",
                    "justification": "? return type makes signature more complex for nothing"
                  }         
                ]
````

If I remove them and run revapi on `xwiki-commons/xwiki-commons-core/xwiki-commons-extension/xwiki-commons-extension-api`, it doesn't fail...

So something seems amiss... probably some fault on my side but I can't see it...

**Comment by vmassol** [comment]
Regarding my last comment, Thomas says that BTW, revapi wrongly reports those as binary-incompatible but that's not true. Could you confirm if it's a bug or if Thomas is wrong?

**Comment by metlos** [comment]
It's got to do something with the package filter for some strange reason. When I remove that filter, the change is correctly caught.

**Comment by metlos** [comment]
Them new features - why can't they ever work the first time ;)

**Comment by metlos** [comment]
`mvn help:effective-pom` gives me:
```xml
          <analysisConfiguration>{
  "revapi": {
    "java": {
      "filter": {
        "packages": {
          "include": ["org\\.xwiki\\..*"],
          "exclude": ["org\\.xwiki\\..*\\.internal(\\..*)?", "org\\.xwiki\\..*\\.test(\\..*)?"]
        }
      }
    }
  }
}</analysisConfiguration>
```

you're missing `"regex": true` there. It should be:
```xml
          <analysisConfiguration>{
  "revapi": {
    "java": {
      "filter": {
        "packages": {
          "regex": true,
          "include": ["org\\.xwiki\\..*"],
          "exclude": ["org\\.xwiki\\..*\\.internal(\\..*)?", "org\\.xwiki\\..*\\.test(\\..*)?"]
        }
      }
    }
  }
}</analysisConfiguration>
```

I've tried the `platform-url-api` with the corrected config and the change was detected. I hope it will be the case for the rest of the modules, too...

**Comment by metlos** [comment]
The reason you got no detected changes was that revapi was only including a package literally called `org\\.xwiki\\..*` (because regex = false by default). There is no such package so all the classes were effectively filtered out.

**Comment by metlos** [comment]
I've added a check against invalid names when matching full names in class and package filters. Those will catch the misconfigurations like yours: 0fe9e0ad427903ef5dc463b87d9c731d48d835aa

**Comment by vmassol** [comment]
Thanks for your help Lukas!

**Comment by metlos** [comment]
I think we've dealt with this. Closing.
