### ISSUE TITLE
Add option to not validate dependencies

### ISSUE THREAD

**Issue by vmassol** [revapi/revapi#38]
When using the maven plugin, it would be nice to have an option so that revapi doesn't check for violations in dependencies.

Right now we have an issue in XWiki where we have one module in xwiki-commons that has violations. So we've added ignores there. However when we build some modules of xwiki-platform that depend on this module they also fail because of the violations. We don't want that since the violations are already known and ignored in xwiki-commons.

I've quickly checked CheckMojo.java but couldn't find a way to tell revapi to not check dependencies. Is that possible, maybe in the configuration file? BTW I couldn't find in the doc a single document providing all the options available to use in the configuration file, does that exist? (I found several different pages but no reference documentation).

Thanks!

**Comment by metlos** [comment]
This will be in the next version of the revapi maven plugin (not sure yet whether that will be 0.4.6 or 0.5.0).
