### ISSUE TITLE
newArtifacts special BUILD value not recognised anymore

### ISSUE THREAD

**Issue by tarilabs** [revapi/revapi#40]
Hello, [in the doc it is described the newArtifacts can have a special "BUILD" value](http://revapi.org/modules/revapi-maven-plugin/examples/comparing-specific-artifacts.html).

Having in a pom like this:
```
          <oldArtifacts>
            <artifact>${project.groupId}:${project.artifactId}:1.0.0</artifact>
          </oldArtifacts>
          <newArtifacts>
            <!-- The special 'BUILD' GAV is used to specify artifacts that were produced during the build of the current project. -->
            <artifact>BUILD</artifact>
          </newArtifacts>
```

fails with error
```
[INFO] --- revapi-maven-plugin:0.5.0:check (check) @ revapi-scratchpad-build ---
[WARNING] Failed to resolve new artifacts: Bad artifact coordinates BUILD, expected format is <groupId>:<artifactId>[:<extension>[:<classifier>]]:<version>. The API analysis will not proceed.
```

I have [a full reproducer with 2 commits](https://github.com/tarilabs/revapi-scratchpad-build/commit/f11fd229bbca046a4b2aa3931b487d4824e9abc5), so you can even `mvn install` version 1.0.0 while checkingout the first commit, and check the result of the comparison and the above mentioned error while checkingout the second commit including the configuration BUILD variable above here. If that helps.

**Comment by metlos** [comment]
Thanks for spotting this. I've updated the docs to not mention the `BUILD` version. The maven plugin will handle the value correctly but will issue a warning about it being deprecated.

This should be present in `revapi-maven-plugin-0.5.1`.
