### ISSUE TITLE
moving methods to super interface inducing false positive errors for method removed

### ISSUE THREAD

**Issue by tarilabs** [revapi/revapi#41]
In version 1.0.0 I have an interface like this
```
public interface MyInterface {
    void method1();
    void method2();
}
```

In version 1.1.0 I create a superinterface and I move method2 from MyInterface to the superinterface
```
public interface SuperInterface {
    void method2();
}
public interface MyInterface extends SuperInterface {
    void method1();

}
```

now, from a `MyInterface` point of view, it is still exposing the two methods, the only difference that method1 is exposed directly, the method2 is inherited by the superinterface. From a client point of view using the `MyInterface`, these still have both the methods.

However I get a failure like:
```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.5.0:check (check) on project revapi-scratchpad-superinterface: The following API problems caused the build to fail:
[ERROR] java.method.removed: method void net.tarilabs.scratchpad.revapi_scratchpad_superinterface.MyInterface::method2(): Method was removed.
[ERROR] 
```

which is a false positive for the reasons above.

This are my revapi versions in pom:
```
        <plugin>
          <groupId>org.revapi</groupId>
          <artifactId>revapi-maven-plugin</artifactId>
          <version>0.5.0</version>
          <dependencies>
            <dependency>
              <groupId>org.revapi</groupId>
              <artifactId>revapi-java</artifactId>
              <version>0.10.0</version>
            </dependency>
          </dependencies>
```

I have [a full reproducer with 2 commits](https://github.com/tarilabs/revapi-scratchpad-superinterface/commit/1399fb452cdf3317c08e304fe2e0fabbf4ca535e#diff-6e84c927e4f28e9ef5b217af90c68afd), so you can even "mvn install" version 1.0.0 while checkingout the first commit, and check the result of the comparison with version 1.1.0 to display the above mentioned error, while checkingout the second commit which moves the method2 to the superinterface. If that helps.

**Comment by metlos** [comment]
I will need to take a look at the other issue you've reported and will do a quick release afterwards. I'm a bit short on time though, so the releases might only come some time at the beginning of September...

**Comment by tarilabs** [comment]
thanks, is good to even just know this is now fixed, and in the pipeline for a release in the near future ;)

**Comment by metlos** [comment]
`revapi-java-0.10.1` should contain the fix for this issue.
