### ISSUE TITLE
revapi gradle plugin

### ISSUE THREAD

**Issue by juherr** [revapi/revapi#42]
I didn't find any revapi gradle plugin and I'm surprised nobody asked it before, but it could be awesome to have one for gradle users.

**Comment by metlos** [comment]
It certainly would be awesome, but I am no Gradle guy, so any help with it would be greatly appreciated...

**Comment by juherr** [comment]
I'm not a gradle lover neither, but it is a good opportunity to start.

I've heard making a gradle plugin into a maven project is not an easy task, but @raphw made it some days ago and has maybe some advices to share.

**Comment by raphw** [comment]
I could not reuse any of the plugin components. As a matter of fact, the both plugins do not share any code. The main problem is to find out at what time you are allowed to call a method of a `Project`, it depends on the state of the build. In the end, it is trial and error.

**Comment by metlos** [comment]
Many thanks for the pointers, I'll see what I can do about it, but frankly I'm flooded with other work right now so no promises...

**Comment by CRogers** [comment]
I've just made a Gradle plugin for Revapi that we're using internally at my company. It's quite simple at the moment and has some strong opinions/defaults based on how we develop software, but is likely useful for other people who want to use Revapi through Gradle:

https://github.com/palantir/gradle-revapi

**Comment by metlos** [comment]
Whoa, that's huge! Thank you!
