### ISSUE TITLE
Broken links on site for mailing lists

### ISSUE THREAD

**Issue by remkop** [revapi/revapi#43]
See http://revapi.org/modules/revapi-maven-plugin/mail-lists.html
and http://revapi.org/modules/revapi/mail-lists.html

The Subscribe link (https://groups.google.com/groups/revapi)
and the Archive link (https://groups.google.com/groups/revapi)
give this error:

> "404. That’s an error.
> The requested URL was not found on this server. That’s all we know."

This link does work: https://groups.google.com/forum/#!forum/revapi

**Comment by metlos** [comment]
Thanks for reporting this! Sort of a thing one rarely checks once set up...
