### ISSUE TITLE
Empty chains when reportUsesFor is turned on

### ISSUE THREAD

**Issue by MarianMacik** [revapi/revapi#46]
Hello,

with java extension 0.11.2 + revapi 0.7.0 when I turn on "reportUsesFor": ["java.method.addedToInterface"] in report, there are no chains. It only looks like: **Use chain of the type in the old API: Use chain of the type in the new API:**.

Thanks.

**Comment by metlos** [comment]
Would you be able to try with the code from the https://github.com/revapi/revapi/tree/bug/46-empty-use-chains branch?

Just check it out, build with `mvn clean install` and use `revapi-maven-plugin` version `0.8.0-SNAPSHOT` and `revapi-java` version `0.12.0-SNAPSHOT`.

I think the changes should fix the problem, but I am not 100% sure the output will be meaningful in a more complex setting.

**Comment by metlos** [comment]
Merged in 127d0e5.

**Comment by MarianMacik** [comment]
I can confirm that with 0.8.0-SNAPSHOT and 0.12.0-SNAPSHOT I am getting use chains. Even though we don't need this right now, it is good for "debugging" of the API changes. Good job!
