### ISSUE TITLE
Annotation filter not behaving correctly

### ISSUE THREAD

**Issue by MarianMacik** [revapi/revapi#47]
Hi,

I have tried to turn on annotation filter and it does not behave as expected. Here is the short reproducer:
https://github.com/MarianMacik/jbpm/tree/revapi-bug - the last commit in this branch contains changes which I deliberately made so revapi will find them. But when annotation filter is turned on (uncomment the part in JSON file which is a part of the last commit), it does not find java.annotation.attributeValueChanged change. When I comment the filter, the report will contain these changes, which is expected.

It is only enough to run mvn clean install -DskipTests in jbpm-audit module.

It behaves the same with 0.6.1 + 0.10.2 and 0.7.0 + 0.11.2 versions.

Thanks,

Marian

**Comment by metlos** [comment]
d95d7c0 should fix this. This will appear in `revapi-java-0.12.0`.

**Comment by MarianMacik** [comment]
I can confirm that it works now. I have only one question: Why are some FQCN written with "\_" character? I mean something like that: java.field.addedStaticField 	field org.jbpm.process.audit.ProcessInstanceLog_.processType 	Static field added to class.

Thanks!

**Comment by metlos** [comment]
huh, that is wrong, isn't it? 😉 could file another issue for this?

**Comment by metlos** [comment]
@MarianMacik  - isn't `org.jbpm.process.audit.ProcessInstanceLog_` a generated class for JPA2 typed queries?

**Comment by MarianMacik** [comment]
I think yes, but then there is no entry with the proper FQCN without underscore. I guess there should be both org.jbpm.process.audit.ProcessInstanceLog_ and org.jbpm.process.audit.ProcessInstanceLog, or not?

**Comment by metlos** [comment]
They should be both in the resulting jar. The `ProcessInstanceLog` is defined in source and `ProcessInstanceLog_` is generated during build and placed in the jar. The API change in `ProcessInstanceLog_` is caused by the change in annotations on methods/fields of `ProcessInstanceLog` I would assume.

**Comment by MarianMacik** [comment]
So is it enough when there is only a change registered for ProcessInstanceLog_ and not for ProcessInstanceLog?

**Comment by metlos** [comment]
not sure ;) is there any change on the `ProcessInstanceLog` class that you see not reported? The change on the `ProcessInstanceLog_` is clearly there but that can be due to some other factors like newer version of the code generator, etc...

**Comment by MarianMacik** [comment]
It seems that changes like added field to the class are reported on classes with "_" and they are referenced as "Static field added to class", though they are definitely not static.

**Comment by metlos** [comment]
When I look in `target/generated-sources` of `jbpm-audit` module, I see the class `ProcessInstanceLog_` with a bunch of `public static volatile` fields. How did you find out the field is not static? I currently cannot reliably build the audit module so I cannot actually check the class file itself, but I assume it is going to look the same as the source.

**Comment by MarianMacik** [comment]
I am sorry, they are static, but the point is I do not get any field-related change in the ProcessInstanceLog without "_" class, I think that is the main point where this change should be visible. And now I rebased it, at least I can build it. So maybe it is a bug, that change to this class - in particular adding another field - is not tracked in class without _ but as a static field inside class with _. Is it understandable? :)

**Comment by metlos** [comment]
Btw. I think in this case, it could be useful to just ignore these generated classes and instead only report on stuff from the actual source. These classes are annotated with `@javax.annotation.Generated` and `@javax.persistence.metamodel.StateMetamodel` annotations so you could filter these classes out of the API check based on those annotations...

**Comment by metlos** [comment]
The reason why `processType` is not reported on `ProcessInstanceLog` is that it is merely a new private field and new getter/setter methods. Such changes are completely source and binary compatible. The addition of a private field is not even reported and the getter/setter methods are reported using `java.method.added` code that is classified as non-breaking (http://revapi.org/modules/revapi-java/differences.html#a_method_added)

**Comment by MarianMacik** [comment]
OK, it is there after adding getter/setter methods, sorry for the confusion :) I have removed javax.persistence.metamodel.* classes and now it works as intended. Thanks!
