### ISSUE TITLE
Make maven plugin's report goal report the justifications for changes.

### ISSUE THREAD

**Issue by metlos** [revapi/revapi#51]
It'll have to disable the ignore extension and read its configuration.

This is kinda breaking, because people by now are probably used to using 2 different configurations for check and report goals.

Also, this ties in with #17 - the matching has its issues.

**Comment by MarianMacik** [comment]
I have just been going to propose this feature, but I have found this thread already here. As we spoke before, it is good to have full report feature. Right now, it can be overcome by having ignores and other config like filters in 2 separate config files and with the report goal only run config without ignore file. When running without ignores, all changes will be there, but no justifications, so it is missing a point a little bit. Good to know that you have already been thinking about this feature. Thanks!
