### ISSUE TITLE
Bug in revapi-java 0.11.* with FieldMovedInHierarchy

### ISSUE THREAD

**Issue by surli** [revapi/revapi#53]
Hi,

i'm setting up revapi for [Spoon](https://github.com/INRIA/spoon) project through maven plugin and it seems there's a bug with `FieldMovedInHierarchy` on version 0.11.1 and 0.11.2 of revapi-java. Everythings work fine with version 0.10.2.

I obtain the following error when executing check goal: 

> Exception in thread "main" java.util.ServiceConfigurationError: org.revapi.java.spi.Check: Provider org.revapi.java.checks.fields.FieldMovedInHierarchy could not be instantiated [...]
Caused by: java.lang.NoSuchFieldError: FIELD_INHERITED_NOW_DECLARED at org.revapi.java.checks.fields.FieldMovedInHierarchy.<init>(FieldMovedInHierarchy.java:17)

The full stack trace is available on this [gist](https://gist.github.com/surli/5ab28fe8f2b1e88ced7e6346e5518a22).

Here's my maven config for revapi:
```
    <plugin>
        <groupId>org.revapi</groupId>
        <artifactId>revapi-maven-plugin</artifactId>
        <version>0.6.1</version>
        <dependencies>
          <dependency>
            <groupId>org.revapi</groupId>
            <artifactId>revapi-java</artifactId>
            <version>0.11.2</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <id>revapi-check</id>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <analysisConfiguration>
            {
              "revapi": {
                "java": {
                  "filter": {
                    "packages": {
                      "regex": true,
                      "include": ["spoon\\..*"],
                      "exclude": ["spoon\\..*\\.test(\\..*)?"]
                    }
                  }
                }
              }
            }
          </analysisConfiguration>
        </configuration>
      </plugin>
```

**Comment by metlos** [comment]
Hi, this is because of #12. Do things work when you use the revapi-maven-plugin 0.7.0?

**Comment by surli** [comment]
Yes it works. My bad I didn't check a new version was released. Thanks!

**Comment by metlos** [comment]
I'm closing this as things kinda work. If you discover any other problems, don't hesitate raise a new issue.
