### ISSUE TITLE
Checking of parameter annotations is not working

### ISSUE THREAD

**Issue by MarianMacik** [revapi/revapi#61]
When I am checking REST resource classes with revapi, changes to @QueryParam("containerId") and other similar parameter annotations are not found in revapi report. I think it is only a small bug since it works quite well on public fields, classes, methods etc. See an example of a class: https://github.com/droolsjbpm/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ExecutorResource.java

Thanks!

Marian

**Comment by metlos** [comment]
Fixed in `revapi-java-0.13.1`.
