### ISSUE TITLE
only consider binary compatibility issues

### ISSUE THREAD

**Issue by monperrus** [revapi/revapi#77]
I'd like to only consider binary compatibility issues with Revapi. How to configure Revapi to **not** consider and fail on source-level issues?

**Comment by metlos** [comment]
Add this snippet to your revapi configuration (or update your `revapi.reclassify` configuration if you so choose):

```javascript
{
  "extension": "revapi.reclassify",
  "configuration": {
    "regex": true,
    "code": ".*",
    "classify": {
      "SOURCE": "EQUIVALENT"
    }
  }
}
```
or if you're using the XML configuration, rewrite the above using the example http://revapi.org/modules/revapi-basic-features/extensions/reclassify.html .

This should lower the severity of the source-incompatibility of any found problem to "equivalent" which is the lowest possible value.

**Comment by monperrus** [comment]
Thanks
