### ISSUE TITLE
move minSeverity from reporter to checker

### ISSUE THREAD

**Issue by monperrus** [revapi/revapi#78]
I have a problem, I configure minSeverity to BREAKING in text.reporter.

However, it happens that `mvn revapi:check` fails yet `mvn revapi:report` says "no change", which is quite confusing.

Hence, I'd like to move the configuration of minSeverity from the reporter to the checker.

How to do this?

**Comment by metlos** [comment]
There is a distinction between the text reporter and maven build failing. The reporter is used to report findings while the maven build is used to break the build or let it pass based on the severity of the found problems.

There are two maven properties that configure the behavior of the build (not the reporting):
* `failBuildOnProblemsFound` - (defaults to true), which you can set to false to never fail the build
* `failSeverity` - (defaults to `potentiallyBreaking`), which you can set to another value to change when the build really fails.

So in your case, I'd change the configuration of the maven plugin to set the `failSeverity` to `breaking` to have a "non-surprising" behavior between the maven plugin and the reporter...

**Comment by monperrus** [comment]
Perfect, this is exactly what I was looking for.

In which JSON block it goes? In block "maven" like below?

```
{
  "revapi": {
    "maven": {
        "failSeverity": "BREAKING",
    }
}
```

**Comment by metlos** [comment]
no, this is part of the configuration of the maven plugin itself, so this is actually the xml in pom:

```xml
<plugin>
  <groupId>org.revapi</groupId>
  <artifactId>revapi-maven-plugin</artifactId>
  <configuration>
    <failSeverity>breaking</failSeverity>
    ...
```

**Comment by monperrus** [comment]
thanks

**Comment by monperrus** [comment]
one more question, does `failSeverity` apply to binary or source level?

**Comment by metlos** [comment]
it applies to whatever is greater...
