### ISSUE TITLE
regression in revapi-reporter-text 0.8.0: no output file written

### ISSUE THREAD

**Issue by monperrus** [revapi/revapi#80]
We have a regression by switching revapi-reporter-text to version 0.8.0.
 
In version 0.7.0, the output report is written in `target` as expected, but in version 0.8.0 nothing is written, and the output file does not exist. 

We use exactly the same configuration file in both cases.

**Comment by metlos** [comment]
I've tried to build spoon master using
```
mvn clean install
```

and got no `target/revapi_report.md` either...

Then I found out that you're missing the execution definition on the `revapi-maven-plugin` in your pom.xml. Adding:

```xml
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
```
to the plugin definition in your pom.xml caused it to normally execute and produce the report in `target` as configured.

How did you invoke your build before that this wasn't an issue?

**Comment by monperrus** [comment]
> How did you invoke your build before that this wasn't an issue?
mvn revapi:report

**Comment by metlos** [comment]
`revapi-reporter-text-0.8.0` is not compatible with revapi API used by `revapi-maven-plugin-0.8.x`.

When I tried spoon build with just the reporter version changed to 0.8.0, I noticed the report being output on standard output using the standard template, which suggests to me that it didn't pick up your configuration at all and just used the defaults.

On the other hand, when I upgrade all your revapi components to the versions that are mutually compatible, i.e.:

```
$ git diff
diff --git a/pom.xml b/pom.xml
index 6036aa2..0033884 100644
--- a/pom.xml
+++ b/pom.xml
@@ -492,17 +492,17 @@
         <groupId>org.revapi</groupId>
         <artifactId>revapi-maven-plugin</artifactId>
         <!-- Lock down plugin version for build reproducibility -->
-        <version>0.8.1</version>
+        <version>0.9.0</version>
         <dependencies>
           <dependency>
             <groupId>org.revapi</groupId>
             <artifactId>revapi-java</artifactId>
-            <version>0.13.1</version>
+            <version>0.14.0</version>
           </dependency>
           <dependency>
             <groupId>org.revapi</groupId>
             <artifactId>revapi-reporter-text</artifactId>
-            <version>0.7.0</version>
+            <version>0.8.0</version>
           </dependency>
         </dependencies>
         <configuration>
```

and then when I run:

```
mvn clean package revapi:report -DskipTests
```

the report is there. Note that it is necessary to run the package phase first if you want to compare the locally built snapshot against the latest snapshot from the server....

**Comment by metlos** [comment]
Oh, I forgot that you can also just use:

```
mvn revapi:report-fork
```

that goal "forks" the `package` lifecycle automatically. This is useful for the commandline but causes issues when used inside a full build, so it is rarely used.

**Comment by monperrus** [comment]
OK thanks
