### ISSUE TITLE
documentation is really hard to browse

### ISSUE THREAD

**Issue by monperrus** [revapi/revapi#81]
**Problem**: I never find what I want on revapi.org

**High-level cause**: the link structure is counter-intuitive, some links are somehow hidden

**Low-level causes**: 

* the top-level menu is dynamic (sometimes it changes with a new "Project Details")
* the project details are visible only upon click (hence one does not find elements with Ctrl-F)
* the "Table of Contents" refers to anchors of the same page and not to other pages of the same sub-project

**Tentative solutions**:

Solution A:
* the top-level menu is stable (always the same items)
* the "Project Details" are put as a new flat horizontal menu below the top menu

Solution B:
* the top-level menu is stable (always the same items)
* the "Project Details" are put on the right hand side, at the same place as the (Anchor) Table of contents
* The  (Anchor) Table of contents is moved at the top or bottom of the page

**Comment by metlos** [comment]
Good suggestions, I'll try to look into it... The current structure is a result of hard fights with maven site plugin and I'm not satisfied with the current state either... I'd me more than happy to merge any pull request in this area if you have more experience than the little I have with the site plugin...

**Comment by monperrus** [comment]
> I'd me more than happy to merge any pull request in this area
OK.

How do you generate the site?

I have an error with "mvn site:site"

**Comment by metlos** [comment]
`mvn clean package site:site -DskipTests`
The reason for that is that revapi creates a report of its own API changes, so it needs the artifacts to be built before the site is generated.

**Comment by monperrus** [comment]
> |mvn clean package site:site -DskipTests|
|OK, it works.|

Instead of tweaking the site plugin, one easy solution is to move the documentation pages from the
submodules to the main one.

WDYT?

**Comment by metlos** [comment]
A long time ago, I had a setup like that, but I changed it to the current scheme, because I didn't like the "distance" from the code to the documentation. I kept on forgetting to update the site, whereas with the current setup, the site is more "in my face" and I am more likely to remember updating it ;) That said, if it is impossible to improve the current state, of course, we'll have to change the setup to one that would support the better navigation.

**Comment by monperrus** [comment]
having looked at the code and doc of the msb3 theme, there is no easy configuration solution, and the only reasonable solution I found is #82. I hope you'll like it too.
