### ISSUE TITLE
Revapi configuration

### ISSUE THREAD

**Issue by MarianMacik** [revapi/revapi#84]
Hi,

it has been a long time since you were on revapi IRC (I have also sent you an email), so I decided to write my issue here. I need an advice about revapi configuration. I may have found a bug, but I am not really sure.

The task is to set revapi in one of our projects in the way that in some package with name _config_ revapi would check everything except for methods which are not getters/setters. So from method methods we only want to check getters/setters. So I have configured it like this:

I am using older way of JSON config, but this shouldn't be a problem. I have configured a general filter for revapi where I can choose elementKind _method_. The configuration is following:

```{
  "filters": {  
    "revapi": {  
      "filter": {  
        "elements": {  
            "exclude": [  
            "method .* org\\.optaplanner\\.core\\.config.*::(?!(set|get)).*"  
            /*"parameter .* org\\.optaplanner\\.benchmark\\.config.*::(?!(set|get)).*"*/  
          ]  
        }  
      },  
.  
.  
.  
```
As you can see I am excluding those methods with the following regex:

```method .* org\\.optaplanner\\.core\\.config.*::(?!(set|get)).*"```

First `.*` is because of different return types and then there is a package name. Second `.*` matches any subpackages and after `::` I have a lookahead `(?!(set|get))` - there mustn't be `get/set` - and the last `.*` matches the remaining part of the method's name including parameters.

I will explain regex ```"parameter .* org\\.optaplanner\\.benchmark\\.config.*::(?!(set|get)).*"``` in a moment.

I have to say that this works for me now. However, there is a one small issue I encountered. When I do not configure revapi this way and I check everything as before, I have to ignore this method:

```
{
  "code": "java.method.numberOfParametersChanged",
  "old": "method void org.optaplanner.benchmark.config.ProblemBenchmarksConfig::buildProblemBenchmarkList(org.optaplanner.benchmark.impl.result.SolverBenchmarkResult)",
  "new": "method void org.optaplanner.benchmark.config.ProblemBenchmarksConfig::buildProblemBenchmarkList(org.optaplanner.core.config.SolverConfigContext, org.optaplanner.benchmark.impl.result.SolverBenchmarkResult)",
  "justification": "PLANNER-448 Benchmark report should state 'Hard score' and 'Soft score' instead of 'Score level 0' and 'Score level 1' by using ScoreDefinition.getLevelLabels()"
}
```

which is fine.

But if I configure revapi filter so it excludes methods that do not begin with ```get/set``` (using the first regex), I have this thing shown up:

```
{
 "code": "java.method.parameterTypeChanged",
 "old": "parameter void org.optaplanner.benchmark.config.ProblemBenchmarksConfig::buildProblemBenchmarkList(===org.optaplanner.benchmark.impl.result.SolverBenchmarkResult===)",
 "new": "parameter void org.optaplanner.benchmark.config.ProblemBenchmarksConfig::buildProblemBenchmarkList(===org.optaplanner.core.config.SolverConfigContext===, org.optaplanner.benchmark.impl.result.SolverBenchmarkResult)",
 "oldType": "org.optaplanner.benchmark.impl.result.SolverBenchmarkResult",
 "newType": "org.optaplanner.core.config.SolverConfigContext",
 "package": "org.optaplanner.benchmark.config",
 "classSimpleName": "ProblemBenchmarksConfig",
 "methodName": "buildProblemBenchmarkList",
 "parameterIndex": "0",
 "elementKind": "parameter",
 "justification": <<<<< ADD YOUR EXPLANATION FOR THE NECESSITY OF THIS CHANGE >>>>>
}
```
It is the same method, but now revapi found different API difference which is the change of the first parameter. It didn't catch the ```numberOfParametersChanged``` as before because it filtered this one out of course - since I have configured the filter. So is this a feature or a bug? :)

If I add the second (commented) regex, it starts to work as intended since I filter this one out too.

My explanation is that in the first case (without filter) it found ```numberOfParametersChanged``` and it did not print out ```parameterTypeChanged``` because it is clear that ```numberOfParametersChanged``` is going on.

In the second case I filtered out ```numberOfParametersChanged``` so revapi at least found ```parameterTypeChanged```, regex did not filter this out, because elementKind is of type ```parameter```.

It is, however, interesting, that other methods do not pose any problems, it is only this very method. For example in the second configuration in the module optaplanner-core I ignore this method (without any filters configured):

```
{
  "code": "java.method.numberOfParametersChanged",
  "old": "method org.optaplanner.core.impl.domain.solution.descriptor.SolutionDescriptor org.optaplanner.core.config.domain.ScanAnnotatedClassesConfig::buildSolutionDescriptor(org.optaplanner.core.config.SolverConfigContext)",
  "new": "method org.optaplanner.core.impl.domain.solution.descriptor.SolutionDescriptor org.optaplanner.core.config.domain.ScanAnnotatedClassesConfig::buildSolutionDescriptor(org.optaplanner.core.config.SolverConfigContext, org.optaplanner.core.impl.score.definition.ScoreDefinition)",
  "justification": "PLANNER-602 Remove <scoreDefinitionType> from the solver configuration."
}
```

So again, it is not a ```get/set``` method as before and again revapi caught it on ```numberOfParametersChanged```. But in this case if I configure the revapi to only catch ```get/set``` methods, I do not get a hit for ```parameterTypeChanged``` as in the first example, so it works as it should. Maybe it is because the order of the parameters stayed the same and the new parameter was added at the end while in the first example the new parameter was added at the beginning, that is why revapi didn't find ```parameterTypeChanged``` in the second example.

Here you can see a commit with the complete configuration:

https://github.com/MarianMacik/optaplanner/commit/15ea4abbf4117e18586b932ced52fe895e76e42b

If you would like to clone it, it is the revapi-master-bug branch.

Thanks for help.

Marian

**Comment by metlos** [comment]
Hi, sorry Marian... Got a new job, IRC blocked here :(

**Comment by metlos** [comment]
Thanks for this detailed report, I will have to look at it in detail because it indeed looks suspicious...

**Comment by MarianMacik** [comment]
Any news on this? I just want to know because I would like to merge the configuration. It is OK if you didn't have time to look on it, I will merge it with the workaround until it's sorted out.

**Comment by metlos** [comment]
Hi Marian,

sorry for the long radio silence on this. I don't have any particular update on this issue apart from the fact that I'm working on revamping the filtering mechanisms to a) make more sense and be generally pluggable already during construction of the API model (to prune out unnecessary stuff early) and b) be much more expressive. I keep this issue in mind when implementing it and want to make sure I fully understand the behavior with the new code.

Hope this doesn't block you..

**Comment by MarianMacik** [comment]
Hi,

good to hear from you! It is not a blocker for us, just an observation which I have found. Anyway, it is a very good tool which we use constantly - I even presented it to our team of 20+ people and they liked it! So thanks for all your wok!

**Comment by metlos** [comment]
I'm closing this with the hopes that https://revapi.org/revapi-java/element-matching.html would be usable for the problem.
