### ISSUE TITLE
add support for short signatures in templates

### ISSUE THREAD

**Issue by monperrus** [revapi/revapi#85]
We use a template as per the documentation as follows:

    Element: ${report.oldElement!"none"} 

The problem is that `report.oldElement` contains the fully-qualifed names of all types involved in the signature. This may be really hard to read: https://github.com/INRIA/spoon/pull/1352#issuecomment-305787739

A great feature would be to a have a readable short signature of elements, without package names:

    Element: ${report.oldElementReadable!"none"}

**Comment by metlos** [comment]
A good idea! It would probably require a configuration parameter of the text reporter and wrapping the report's elements in some custom impls that would override the `toString()`.

As you've probably noticed I've been short on time lately, so any contribution would be gladly welcome (I keep your doc updates in mind and will get back to them as soon as possible)...

**Comment by monperrus** [comment]
We really need this. I can have a look. 

Could you point me to the location to change?

**Comment by MarianMacik** [comment]
@monperrus How come you have so nice reports? Did you extend the reporter or made one yourself? Thanks!

**Comment by monperrus** [comment]
> How come you have so nice reports?

@surli made this nice revapi template: https://github.com/INRIA/spoon/blob/master/chore/revapi_tpl.ftl

**Comment by metlos** [comment]
Btw. I'm hoping this should be fairly easy if we can persuade Freemarker to introspect the beans we're supplying to it. If we can persuade it correctly evaluate this: `report.oldElement.declaringElement.simpleName` then we should actually be done. The `declaringElement` is a property on any [`JavaModelElement`](https://github.com/revapi/revapi/blob/master/revapi-java-spi/src/main/java/org/revapi/java/spi/JavaModelElement.java) which revapi represents the different java elements (types, methods, ...) and each such element as a "simpleName", which in case of classes is the name without the package.

If making the name "pretty" for methods and others would make the template too complex, we can think about other options.

**Comment by metlos** [comment]
@monperrus I'm hoping all the code changes we would have to make would be in https://github.com/revapi/revapi/blob/master/revapi-reporter-text/src/main/java/org/revapi/reporter/text/TextReporter.java and of course the freemarker templates...

**Comment by metlos** [comment]
> Btw. I'm hoping this should be fairly easy if we can persuade Freemarker to introspect the beans we're supplying to it.

This works actually. I was testing it using a private class that Freemarker had trouble introspecting. But it works with a public class.

**Comment by monperrus** [comment]
Cool!

`report.oldElement.declaringElement.simpleName` is OK for a class name.

but I guess that for a method, this would not give the method signature with parameters?

**Comment by metlos** [comment]
PR coming your way ;)

**Comment by metlos** [comment]
https://github.com/INRIA/spoon/pull/1697

**Comment by metlos** [comment]
This seems to be possible with the current functionality as can be seen in the above PR. I will close this issue and will open another one to improve docs on the power of Freemarker and the data we're supplying to it.
