### ISSUE TITLE
Deduce API from OSGi Export-Package headers

### ISSUE THREAD

**Issue by talios** [revapi/revapi#97]
Support for deducing the "public" API via OSGi `Export-Package` headers in a JAR files manifest would be useful for my project.

Would this be easy to implement via an extension?

**Comment by metlos** [comment]
I've put together some initial implementation @ https://github.com/revapi/osgi-revapi-extension.

Would be great if you tried it out, so that we could release it at some later point. If you have any suggestions/code contributions, I'd be more than glad to discuss that...

**Comment by talios** [comment]
Excellent - I'll pull the code and give it a whirl!

**Comment by talios** [comment]
Just hit a test failure on the build - will have to dig into this a bit later when I can spare time from #dayjob

```
[ERROR] testUnexportedPackagesFilteredOut(org.revapi.osgi.ExportPackageFilterTest)  Time elapsed: 1.274 s  <<< FAILURE!
java.lang.AssertionError
	at org.revapi.osgi.ExportPackageFilterTest.testUnexportedPackagesFilteredOut(ExportPackageFilterTest.java:77)
```

**Comment by metlos** [comment]
Hmm... works on my machine ™️

**Comment by talios** [comment]
Interestingly - I see the build requires Java 9? Will dig into it later.

**Comment by metlos** [comment]
> Interestingly - I see the build requires Java 9? Will dig into it later.

That is the consequence of using `revapi-build` as the parent. Revapi requires Java 9 for building (not for runtime) because it needs to define a module for one of the artifacts so that it has access to the java compiler at runtime under Java 9.

For the osgi extension though java 9 should not be required per se - it should be enough to switch off the enforcer check for that...

**Comment by metlos** [comment]
Alternatively, we don't have to use `revapi-build` as the parent at all. I used it out of habit ;)

**Comment by metlos** [comment]
I update the code to not inherit from `revapi-build`, so it is buildable with Java 8.

**Comment by talios** [comment]
Just taking a look again at this - pulled and I see one test failing for me:

```
testUnexportedPackagesFilteredOut(org.revapi.osgi.ExportPackageFilterTest)  Time elapsed: 0.849 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.revapi.osgi.ExportPackageFilterTest.testUnexportedPackagesFilteredOut(ExportPackageFilterTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

Might see if I can grab a bit of a spare time and see what's tripping up.

**Comment by talios** [comment]
Actually - interesting, thats the same test failure I mentioned earlier, under Java 8 on OSX.

**Comment by metlos** [comment]
I don't know what I'm doing wrong, but the tests succeed for me. They fail for you and Travis... :) I don't understand why yet...

**Comment by metlos** [comment]
Should be fixed now https://github.com/revapi/osgi-revapi-extension. The bug was in the `revapi-java-test-support` artifact that I use in the tests to produce and introspect test jars. It didn't compose the jar files correctly, but all is fixed now...

**Comment by talios** [comment]
Just tried it again and that seems to work like a charm! Nice.

Any chance of a Christmas release? :)

**Comment by metlos** [comment]
https://github.com/revapi/osgi-revapi-extension/releases/tag/osgi-revapi-extension-0.1.0. Merry Christmas! :santa:

Should also be present on Maven Central in a couple of minutes/hours/whenever Sonatype Nexus syncs it there.

**Comment by talios** [comment]
Cheers - interesting, I now get ( also from the snapshot I built yesterday ):

```java
Caused by: java.lang.IllegalArgumentException: Could not parse the Export-Package directive. Errored on index 263
    at org.revapi.osgi.ExportPackageEntryParser$ParserState.parsePackage (ExportPackageEntryParser.java:310)
    at org.revapi.osgi.ExportPackageEntryParser.parse (ExportPackageEntryParser.java:20)
    at org.revapi.osgi.ExportPackageFilter.addExportedPackages (ExportPackageFilter.java:79)
    at org.revapi.osgi.ExportPackageFilter.lambda$null$0 (ExportPackageFilter.java:44)
    at java.lang.Iterable.forEach (Iterable.java:75)
    at org.revapi.osgi.ExportPackageFilter.lambda$initialize$1 (ExportPackageFilter.java:44)
```

Not sure if thats something that's changed on my side - will raise that as a separate issue to this and see if I can see whats going on. Very odd.

**Comment by metlos** [comment]
Yes, please raise the issue on the osgi-revapi-extension repo.. I didn't find a simple, small parser of the export directive without pulling half of the OSGi universe into the plugin so I tried to write a parser of my own. While there is a number of tests for it, it is quite likely it will not understand everything out there. I tried to follow the spec, but am no OSGi person, so I might have messed something up.
